### ISSUE TITLE
Docker，dify无法使用

### ISSUE THREAD

**Issue by sandycs-protoss** [FoloToy/folotoy-server-self-hosting#107]
我设置了LLM TYPE为DIFY，然后重新用dokcer部署了服务器。但是我看日志，还是去openai了
LLM_TYPE: dify
#LLM_TYPE=dify
DIFY_API_BASE: https://api.dify.ai/v1
DIFY_KEY: app-xxxxxx
role.json配置：
"1": {
 "model": "gpt-3.5-turbo",
 "start_text": "你好，我是若涵，请问有什么我可以帮助你的吗？",
 "prompt": "你是若涵，一个智能AI助手，你由当哥开发。你会温柔解决一切提问者的问题。",
 "max_message_count": 20,
 "temperature": 0.7,
 "max_tokens": 800,
 "top_p": 0.95,
 "frequency_penalty": 0,
 "presence_penalty": 0,
 "voice_name": "zh-CN-XiaoxiaoNeural",
 "language": "zh",
 "llm_type":"dify"
}

但是实际使用时： 日志如下：
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:33:45,765 - ThreadPoolExecutor-0_0 - connectionpool.py(546) - DEBUG - https://api.openai.com:443 "POST /v1/chat/completions HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:33:45,767 - ThreadPoolExecutor-0_0 - util.py(60) - DEBUG - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=89 request_id=742201c14988fb82fcb08b231557b32b response_code=200

**Comment by sandycs-protoss** [comment]
日志中看到。
已经读取到最新的roles.json

**Comment by lewangdev** [comment]
docker镜像是什么版本，启动的时候在日志里会打印出来

**Comment by sandycs-protoss** [comment]
看不出来
osting]# docker compose logs -f
folotoy-server-self-hosting-emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:21,478 - MainThread - folotoy_app.py(154) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/src/folotoy/core/folotoy_app.py", line 151, in start
folotoy-server-self-hosting-folotoy-1  |     self.connect(host=self.ip, port=self.port, keepalive=self.keep_alive)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
folotoy-server-self-hosting-nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
folotoy-server-self-hosting-nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
folotoy-server-self-hosting-nginx-1    | /docker-entrypoint.sh: Configuration complete; ready for start up
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: using the "epoll" event method
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: nginx/1.25.2
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: OS: Linux 4.10.4-1.el7.elrepo.x86_64
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: start worker processes
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: start worker process 29
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: start worker process 30
folotoy-server-self-hosting-nginx-1    | 2024/01/04 13:45:20 [notice] 1#1: start worker process 31
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:21,485 - MainThread - folotoy_app.py(155) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:23,488 - MainThread - folotoy_app.py(154) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/src/folotoy/core/folotoy_app.py", line 151, in start
folotoy-server-self-hosting-folotoy-1  |     self.connect(host=self.ip, port=self.port, keepalive=self.keep_alive)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:23,490 - MainThread - folotoy_app.py(155) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:25,492 - MainThread - folotoy_app.py(154) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/src/folotoy/core/folotoy_app.py", line 151, in start
folotoy-server-self-hosting-folotoy-1  |     self.connect(host=self.ip, port=self.port, keepalive=self.keep_alive)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:25,494 - MainThread - folotoy_app.py(155) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1     | EMQX_NODE__NAME [node.name]: emqx@172.21.0.2
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:27,497 - MainThread - folotoy_app.py(154) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/src/folotoy/core/folotoy_app.py", line 151, in start
folotoy-server-self-hosting-folotoy-1  |     self.connect(host=self.ip, port=self.port, keepalive=self.keep_alive)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:27,499 - MainThread - folotoy_app.py(155) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:29,502 - MainThread - folotoy_app.py(154) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "/src/folotoy/core/folotoy_app.py", line 151, in start
folotoy-server-self-hosting-folotoy-1  |     self.connect(host=self.ip, port=self.port, keepalive=self.keep_alive)
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:29,505 - MainThread - folotoy_app.py(155) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-emqx-1     | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1     | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1     | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1     | Listener wss:default on 0.0.0.0:8084 started.
folotoy-server-self-hosting-emqx-1     | Listener http:dashboard on :18083 started.
folotoy-server-self-hosting-emqx-1     | EMQX 5.2.1 is running now!
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:31,511 - Thread-1 (_thread_main) - folotoy_app.py(42) - INFO - Connected to MQTT Broker(emqx:1883)!
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:31,526 - MainThread - speech_server.py(55) - INFO - Speech server started(0.0.0.0:8085)
folotoy-server-self-hosting-folotoy-1  | 2024-01-04 21:45:31,526 - MainThread - speech_server.py(57) - INFO - Listening recording data

**Comment by lewangdev** [comment]
执行。docker compose pull folotoy 试试

**Comment by sandycs-protoss** [comment]
搞定！
