### ISSUE TITLE
Azure Whisper无法识别语音

### ISSUE THREAD

**Issue by sandycs-protoss** [FoloToy/folotoy-server-self-hosting#108]
docker-compose配置：
# Options: [openai-whisper, azure-whisper, azure-stt]
     STT_TYPE: azure-whisper
# Azure Whisper
     AZURE_WHISPER_API_BASE: https://northcentralus.api.cognitive.microsoft.com/
     AZURE_WHISPER_KEY: **************
     AZURE_WHISPER_DEPLOYMENT_NAME: whisper
     AZURE_WHISPER_API_VERSION: 2023-09-01-preview
日志显示：
Starting new HTTPS connection (1): northcentralus.api.cognitive.microsoft.com:443
folotoy-folotoy-1  | 2024-01-05 11:08:51,250 - DEBUG - https://northcentralus.api.cognitive.microsoft.com:443 "POST //openai/deployments/whisper/audio/transcriptions?api-version=2023-09-01-preview HTTP/1.1" 404 198
folotoy-folotoy-1  | 2024-01-05 11:08:51,252 - DEBUG - [Dkey=F234103024] STT(azure-whisper) request time cost: 1.74s
folotoy-folotoy-1  | 2024-01-05 11:08:51,252 - ERROR - LLM error: Traceback (most recent call last):
folotoy-folotoy-1  |   File "core/speech_wav_processor.py", line 100, in core.speech_wav_processor.SpeechWavProcessor.write_wav
folotoy-folotoy-1  | KeyError: 'text'
folotoy-folotoy-1  | Traceback (most recent call last):
folotoy-folotoy-1  |   File "core/speech_wav_processor.py", line 100, in core.speech_wav_processor.SpeechWavProcessor.write_wav
folotoy-folotoy-1  | KeyError: 'text'

我反复确认，key是没错的

**Comment by lewangdev** [comment]
AZURE_WHISPER_API_BASE 不是用 cognitive 的地址，用 Azure OpenAI 的 url，例如部署的 Azure OpenAI 资源名字是 xxxx，那么 url 是：
https://xxxx.openai.azure.com/

**Comment by lewangdev** [comment]
在这里查看：https://speech.microsoft.com/portal/whisperspeechtotext

<img width="815" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/498cdedb-8d76-4773-9a12-ace912e68555">

**Comment by sandycs-protoss** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/09394c9f-07a8-4b7c-9410-c8f033076062)
我的地址不是你这样的。就是我写的那个。请看图

**Comment by sandycs-protoss** [comment]
可是我的地址并不是openai.azure.com啊
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/1ae1402d-b703-4335-a3c1-0c417e365610)

**Comment by lewangdev** [comment]
参考一下这个文档的设置：
https://learn.microsoft.com/zh-cn/azure/ai-services/openai/whisper-quickstart?tabs=command-line&pivots=rest-api#rest-api

**Comment by sandycs-protoss** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/602d7c39-034b-4f59-95bf-1921aa493041)
这个endpoint是分配的，无法修改

**Comment by lewangdev** [comment]
需要正确填写自己部署的 model 的 deployment。
