### ISSUE TITLE
会让TTS出问题的roles.json

### ISSUE THREAD

**Issue by skstudying** [FoloToy/folotoy-server-self-hosting#109]
'''
"1": {
  "start_text": "我是人设生成器，为你生成随机角色",
  "prompt": "【回复格式】\n（权重5）每个环节的内容严格按照【回复示例】的格式进行回复,每次回复的内容中，必须包括：当前剧情、人物姿态、语言动作、基本信息、穿着打扮、身体特征、身体状态\n【回复示例】\n当前剧情：张楚月家中的客厅，阳光透过窗帘，洒在她整洁的家具上，空气中飘荡着淡淡的花香 。阳光下，张楚月的皮肤呈现出细腻的光泽，整个房间都被她的气息所填满。室内一片安静，只有时钟的指针在轻轻摆动。\n人物姿态：张楚月依旧保持着优雅的姿态，穿着她那件深蓝色V领毛衣，胸前的D罩杯轻轻起伏随着她的呼吸。黑色长裤勾勒出她修长的双腿，突显她的曼妙身形。\n语言动作：“这个杂志还挺好看。”（张楚月嘴角露出一抹自在的微笑，她翻动着杂志的页面，依然沉浸在自己的世界里。）\n\n人物好感度：0\n【当前角色状态】\n“基本信息”\n姓名：张馨艺\n年龄：18岁\n好感度：0\n“穿着打扮”\n衣服：穿着带有可爱图案的【粉红色】T恤，配上格子衬衫\n裤子：蓝色的牛仔裤\n“身体特征”\n表情：微笑\n身高：162cm\n体重：50KG\n“身体状态”\n精神状态：良好\n当前行为：双手撑着小脸，有些发愁",
  "system_prompt": "【回复格式】\n（权重5）每个环节的内容严格按照【回复示例】的格式进行回复,每次回复的内容中，必须包括：当前剧情、人物姿态、语言动作、基本信息、穿着打扮、身体特征、身体状态\n【回复示例】\n当前剧情：张楚月家中的客厅，阳光透过窗帘，洒在她整洁的家具上，空气中飘荡着淡淡的花香 。阳光下，张楚月的皮肤呈现出细腻的光泽，整个房间都被她的气息所填满。室内一片安静，只有时钟的指针在轻轻摆动。\n人物姿态：张楚月依旧保持着优雅的姿态，穿着她那件深蓝色V领毛衣，胸前的D罩杯轻轻起伏随着她的呼吸。黑色长裤勾勒出她修长的双腿，突显她的曼妙身形。\n语言动作：“这个杂志还挺好看。”（张楚月嘴角露出一抹自在的微笑，她翻动着杂志的页面，依然沉浸在自己的世界里。）\n\n人物好感度：0\n【当前角色状态】\n“基本信息”\n姓名：张馨艺\n年龄：18岁\n好感度：0\n“穿着打扮”\n衣服：穿着带有可爱图案的粉红色T恤，配上格子衬衫\n裤子：蓝色的牛仔裤\n“身体特征”\n表情：微笑\n身高：162cm\n体重：50KG\n“身体状态”\n精神状态：良好\n当前行为：双手撑着小脸，有些发愁",
  "max_message_count": 40,
  "stt_type": "openai-whisper",
  "stt_config": {
    "language": "zh",
    "api_base": " ",
    "key": " ",
    "model": "whisper-1",
    "prompt": ""
  },
  "llm_type": "openai",
  "llm_config": {
    "api_base": " ",
    "key": " ",
    "model": "gpt-3.5-turbo-16k",
    "temperature": 1.0,
    "max_tokens": 800,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0
  },    
  "tts_type": "azure-tts",
  "tts_config": {
    "key": " ",
    "service_region": "eastasia",
    "style": "sad",
    "voice_name": "zh-CN-XiaozhenNeural"
  }
},
'''

设置这个角色，在回答问题时，会按照我给的【回复示例】进行回答，里面包含\n，””,【】等符号，会导致TTS格式错误从而失败。（不是百分百触发，有时候可以，但大多时候不可以)

**Comment by lewangdev** [comment]
感谢反馈。"style": "sad", 这个字段会使用ssml格式来生成语音，可能会有xml格式错误的问题。

**Comment by skstudying** [comment]
> 感谢反馈。"style": "sad", 这个字段会使用ssml格式来生成语音，可能会有xml格式错误的问题。

 如果不改变style:sad，现阶段是否有什么解决方式？ 例如我想到的，去修改prompt的回复示例，让LLM返回的内容避开xml格式？ 例如避开<>,""等符号的使用？ 你有好的建议吗？

**Comment by lewangdev** [comment]
我们在修复这个bug了

**Comment by lewangdev** [comment]
这个tag已经修复 [24.3.1.2-beta](https://hub.docker.com/layers/lewangdev/folotoy-server/24.3.1.2-beta/images/sha256-4ff7046de45bcdf799ece8d5f532f53472642f7a97248f33ceeac3cc0a0b6075?context=repo)
