### ISSUE TITLE
开源模型配置

### ISSUE THREAD

**Issue by hxmilyy** [FoloToy/folotoy-server-self-hosting#111]
请问如果要使用其他的STT、LLM、TTS模型，比如千问、chatglm，还有https://x.com/lewangx/status/1730172194553286874?s=12 ，这里提到的那些TTS、STT模型，要怎么实现？

**Comment by lewangdev** [comment]
需要自己实现对应的接口，例如 STT、LLM、TTS 都可以做成与 OpenAI 一样的接口，然后在配置文件里面启用自己的接口，就可以了

**Comment by lewangdev** [comment]
参考这里：https://github.com/FoloToy/folotoy-server-self-hosting/issues/83

**Comment by hxmilyy** [comment]
是要自己实现folotoy服务器的逻辑吗

**Comment by lewangdev** [comment]
不需要的，只用实现对应的接口

**Comment by hxmilyy** [comment]
请问对应的接口约束去哪找🙏

**Comment by lewangdev** [comment]
查看openai官方的接口文档，或者参考我的开源实现
