### ISSUE TITLE
怎么安装本地的faster-whisper

### ISSUE THREAD

**Issue by lkyuier** [FoloToy/folotoy-server-self-hosting#115]
https://github.com/lewangdev/faster-whisper  就是这个项目，我如果在本地使用，是不是要自己写api接口？

**Comment by lkyuier** [comment]
> 需要自己参考我们的实现开发满足自己要求的代码，基本操作是把项目里三个requirements文件都安装好，然后参考fastapi项目启动接口，
> 
> 如果遇到安装依赖和环境的问题，需要自己看日志去相应的开源项目哪里去看文档解决

我看有个log-config.yml的文件，是不是docker-compose启动这个文件就行了？？？

**Comment by lewangdev** [comment]
是faster-whisper，不是 fast-whisper

**Comment by lewangdev** [comment]
> > 需要自己参考我们的实现开发满足自己要求的代码，基本操作是把项目里三个requirements文件都安装好，然后参考fastapi项目启动接口，
> 
> > 
> 
> > 如果遇到安装依赖和环境的问题，需要自己看日志去相应的开源项目哪里去看文档解决
> 
> 
> 
> 我看有个log-config.yml的文件，是不是docker-compose启动这个文件就行了？？？
> 

不是，这个是fastapi的配置
