### ISSUE TITLE
怎么看log

### ISSUE THREAD

**Issue by lkyuier** [FoloToy/folotoy-server-self-hosting#116]
王哥，我在部署了一台服务器在香港用来和火火兔对话，可
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/48005813/40fbcce3-0097-4138-a080-94cadbc0a1d2)
是经常就没信息了，不知道哪里出问题了，哪个工程可以查看下log，我想确认我的信息发过去了，或许只是Openai的key不对一类，现在完全没有头绪，没法对话

**Comment by lewangdev** [comment]
这里：https://docs.folotoy.com/zh/docs/faq

**Comment by lkyuier** [comment]
那个服务直接和火火兔交互，我不知道哪个环节出问题了，按下录音，松手后，一直没有返回，应该可以有什么log可以追查下吧？

**Comment by lewangdev** [comment]
你的vps是香港的吗？OpenAI不允许香港ip使用的

**Comment by lkyuier** [comment]
我换成了新加坡的节点后，就一直是兔子耳朵闪烁成黄绿色，能不能帮我看看，

**Comment by lewangdev** [comment]
你用的是那家vps？ 方便的话，把你的vps的ip用户名密码发到我邮箱 lewang.dev@gmail.com
