### ISSUE TITLE
Azure-stt 无法使用

### ISSUE THREAD

**Issue by Bossjava** [FoloToy/folotoy-server-self-hosting#117]
错误日志

> 2024-01-24 21:36:58,077 - DEBUG - Received token: 2d5ea579366847e487f834e98e2811d3 RecordingId: 4
> 2024-01-24 21:36:58,077 - DEBUG - Received frame type: b'\x02'
> 2024-01-24 21:36:58,078 - DEBUG - Recording file created: /audio/recording-211cc5a216fd4ed8b7bd6756e0053cc8.wav
> 2024-01-24 21:36:58,078 - DEBUG - Current dkey=24dcc3d0c644 role=7
> 2024-01-24 21:36:58,078 - DEBUG - STT type: azure-stt
> 2024-01-24 21:36:58,553 - WARNING - Speech Recognition canceled: CancellationReason.Error
> 2024-01-24 21:36:58,553 - WARNING - Error details: WebSocket upgrade failed: Bad request (400). Error details: Failed with HTTP 400 Bad Request
> wss://eastasia.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=zh
> X-ConnectionId: 4ae9b4a2b6f0474fb5c9bc345b71a030 Please verify the provided subscription details and language information. SessionId: 4ae9b4a2b6f0474fb5c9bc345b71a030
> 2024-01-24 21:36:58,553 - WARNING - Did you set the speech resource key and region values?
> 2024-01-24 21:36:58,570 - DEBUG - [Dkey=24dcc3d0c644] STT(azure-stt) request time cost: 0.49s
> 2024-01-24 21:36:58,570 - INFO - Dkey 24dcc3d0c644: Transcript is empty

我的 `docker-compose.yml` 配置

> version: '3'
> 
> services:
>  emqx:
>    image: emqx/emqx:latest
>    restart: always
>    ports:
>      - "1883:1883/tcp"
>      - "18083:18083/tcp"
>      - "8083:8083/tcp"
>    volumes:
>      - emqx-data:/opt/emqx/data
>      - emqx-log:/opt/emqx/log
>  nginx:
>    image: nginx:latest
>    restart: always
>    ports:
>      - "8082:80/tcp"
>    volumes:
>      - ./audio:/usr/share/nginx/html
>  folotoy:
>    image: lewangdev/folotoy-server:latest
>    restart: always
>    depends_on:
>      emqx:
>          condition: service_started
>      nginx:
>          condition: service_started
>    ports:
>      - "8085:8085/udp"
>    volumes:
>      - ./audio:/audio
>      - ./roles.json:/roles.json
>    environment:
>      TZ: Asia/Shanghai

>      LOG_LEVEL: DEBUG
> 
>      ROLES_FILE_PATH: /roles.json
> 
>      # Default STT(Sound To Text) type
>      # Options: [openai-whisper, azure-whisper, azure-stt]
>      STT_TYPE: azure-stt
> 
>      # OpenAI Whisper
>      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.cc/v1
>      #OPENAI_WHISPER_API_BASE: https://oneapi.huinong.co/v1
>      #OPENAI_WHISPER_KEY: sk-
>      #OPENAI_WHISPER_API_BASE: https://chatapi.onechat.fun/v1
>      #OPENAI_WHISPER_KEY: sk-
>      #OPENAI_WHISPER_API_BASE: https://sapi.onechat.fun/v1
>      #OPENAI_WHISPER_KEY: sk-
>      #OPENAI_WHISPER_MODEL: whisper-1
>      
>      # Azure Whisper
>      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
>      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
>      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
>      AZURE_WHISPER_API_VERSION: 2023-09-01-preview
> 
>      # Azure STT https://eastasia.api.cognitive.microsoft.com/
>      AZURE_STT_KEY: 45117d5d89914
>      AZURE_STT_SERVICE_REGION: eastasia
> 
>      # Default LLM(Large Language Model) type
>      # Options: [openai, azure-openai]
>      LLM_TYPE: openai
> 
>      # OpenAI
>      #https://one-api.xxx.cc/v1
>      #OPENAI_OPENAI_API_BASE: https://oneapi.huinong.co/v1
>      #OPENAI_OPENAI_KEY: sk-
>      #OPENAI_OPENAI_API_BASE: https://chatapi.onechat.fun/v1
>      #OPENAI_OPENAI_KEY: sk-
>      #OPENAI_OPENAI_API_BASE: https://sapi.onechat.fun/v1
>      #OPENAI_OPENAI_KEY: sk-
>      OPENAI_OPENAI_API_BASE: http://124.221.29.88:3000/v1
>      OPENAI_OPENAI_KEY: sk-
> 
>      #Azure OpenAI
>      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
>      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
>      AZURE_OPENAI_API_VERSION: "2023-05-15"
> 
>      #LLM_TYPE=dify
>      DIFY_API_BASE: http://192.168.52.88/v1
>      DIFY_KEY: app-zm56c2HRiIWRXsR67jfnrmCE
> 
>      #Baidu YIYAN API
>      #LLM_TYPE: yiyan
>      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
>      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx
> 
>      # If your elevenlabs is a free account, keep 2 here
>      VOICE_EXECUTOR_MAX_WORKERS: 2
> 
>      # Default TTS(Text to Sound) type
>      # Options: [edge-tts, azure-tts, elevenlabs, openai-tts]
>      # edge-tts is Free but slow
>      # If you change TTS_TYPE to other option, please modify roles.json
>      # https://docs.folotoy.com/zh/docs/configuration/roles_config
>      TTS_TYPE: azure-tts
> 
>      # Azure TTS
>      AZURE_TTS_KEY: 45117d5d8991
>      AZURE_TTS_SERVICE_REGION: eastasia
> 
>      # elevenlabs
>      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
>      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2
> 
>      # OpenAI TTS
>      #OPENAI_TTS_API_BASE: https://one-api.xxx.cc/v1
>      #OPENAI_TTS_API_BASE: https://oneapi.huinong.co/v1
>      #OPENAI_TTS_KEY: sk-
>      #OPENAI_TTS_API_BASE: https://chatapi.onechat.fun/v1
>      #OPENAI_TTS_KEY: sk-
>      #OPENAI_TTS_API_BASE: https://sapi.onechat.fun/v1
>      #OPENAI_TTS_KEY: sk-
>      #OPENAI_TTS_MODEL: tts-1  
> 
>      AUDIO_DOWNLOAD_URL: http://124.221.29.88:8082
>      AUDIO_SAVE_PATH: /audio
> 
>      # MQTT Broker
>      MQTT_BROKER_HOST: emqx
>      MQTT_BROKER_PORT: 1883
>      MQTT_CLIENT_ID: folotoy
>      MQTT_USERNAME: folotoy
>      MQTT_PASSWORD: folotoy
> 
>      SPEECH_UDP_SERVER_HOST: 124.221.29.88
>      SPEECH_UDP_SERVER_PORT: 8085
> 
> volumes:
>  emqx-data:
>  emqx-log:

**Comment by lewangdev** [comment]
roles.json 中要设置正确的 language 代码，如果使用的是 azure-stt，那么要设置 auzre-stt的语言代码，例如是 zh-CN
