### ISSUE TITLE
用了新加坡节点后，兔子耳朵一直闪烁成黄绿色

### ISSUE THREAD

**Issue by lkyuier** [FoloToy/folotoy-server-self-hosting#118]
兔子耳朵闪烁成黄绿色，用了新加坡节点后，请问怎么看log？

**Comment by lewangdev** [comment]
> 兔子耳朵闪烁成黄绿色，用了新加坡节点后，请问怎么看log？

参考这里
https://docs.folotoy.com/zh/docs/faq

**Comment by lewangdev** [comment]
发一些你的日志。

应该不会出现绿色变成蓝色的，目前没有这个逻辑。是否是变成白色，蓝色是配网才会出现。或者发生了重启，重新联网失败进入配网

**Comment by lkyuier** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/48005813/0f79c8fb-3b52-4900-a0c3-2023deadd5ec) 
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/48005813/885910b7-ca99-42ea-b6f1-2ae17a7bf033)
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/48005813/43ebe5c5-512d-4772-b46d-adfb692f2c1e)

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/48005813/6681d33f-2879-4b54-96c8-1f3c9cc56d8c)
请帮忙看看吗，除了第一声,hi，有什么可以帮你的吗，然后就再也没有返回了

**Comment by lewangdev** [comment]
日志不全，能发全部的日志吗？把玩具关机再开机一下就能看到很多日志了
