### ISSUE TITLE
刷机和配置教程

### ISSUE THREAD

**Issue by lewangdev** [FoloToy/folotoy-server-self-hosting#12]
https://github.com/FoloToy/folotoy-tool/wiki

* [刷机说明](https://github.com/FoloToy/folotoy-tool/wiki/%E5%88%B7%E6%9C%BA%E8%AF%B4%E6%98%8E)
* [配网说明](https://github.com/FoloToy/folotoy-tool/wiki/%E9%85%8D%E7%BD%91%E8%AF%B4%E6%98%8E)

**Comment by liugod** [comment]
这个配网说明没有说清楚那个服务器地址怎么填，以及如果用官方服务器怎么填。
