### ISSUE TITLE
微软openai的tts好像并没有提供支持，后续有计划吗？

### ISSUE THREAD

**Issue by afterhill** [FoloToy/folotoy-server-self-hosting#132]
<img width="1058" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/2742842/33280bdc-f469-4c72-a7c5-f5fa34016627">

**Comment by lewangdev** [comment]
谢谢反馈，我们去看一下

**Comment by lewangdev** [comment]
已经对接好了，这周发布的版本会支持 Azure OpenAI TTS

**Comment by lewangdev** [comment]
最新版已经发布了，sudo docker compose pull 下载最新镜像即可使用，配置文档：https://docs.folotoy.com/zh/docs/configuration/roles_config#%E6%96%87%E5%AD%97%E8%BD%AC%E8%AF%AD%E9%9F%B3-tts-text-to-sound-%E8%A7%92%E8%89%B2%E7%BA%A7%E5%88%AB%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

<img width="979" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/585c59ab-908e-442b-8135-b1fa90ecbba5">
<img width="1071" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/0c74543e-0b5c-497b-9b1b-d72e3e1abc98">
