### ISSUE TITLE
回传的TTS没读完

### ISSUE THREAD

**Issue by tanaer** [FoloToy/folotoy-server-self-hosting#136]
# 服务端日志

```
2024-03-18 23:21:45,923 - DEBUG - Publish topic: /user/folotoy/24dcc3d0c644/thing/command/call, msg: {"msgId": 17, "identifier": "audioplay", "inputParams": {"recordingId": 4, "order": 1, "url": "http://124.221.x:8082/voice-7b73713027204bf3aa671a396c1abb92.mp3"}}
2024-03-18 23:21:45,923 - DEBUG - [Dkey=24dcc3d0c644]: Recording Id: 4, Order: 3 Content: 闪电深吸了一口气，准备开始跳跃。它首先跳到了第一块石头上，稳稳地落在了上面。然后，它又跳到了下一块石头，就这样，一块接一块，闪电像在跳舞一样轻盈地跳过了溪流。
2024-03-18 23:21:45,925 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-03-18 23:21:46,260 - DEBUG - Received /user/folotoy/24dcc3d0c644/thing/command/callAck: message data: {'msgId': 17, 'identifier': 'audioplay', 'result': 1}
2024-03-18 23:21:46,260 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d0c644']}
2024-03-18 23:21:46,651 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 200 None
2024-03-18 23:21:46,800 - DEBUG - ChatCompletion request time cost: 11.17s
2024-03-18 23:21:49,150 - DEBUG - TTS(aliyun-tts) request time cost: 9.25s
2024-03-18 23:21:49,151 - DEBUG - Publish topic: /user/folotoy/24dcc3d0c644/thing/command/call, msg: {"msgId": 18, "identifier": "audioplay", "inputParams": {"recordingId": 4, "order": 2, "url": "http://124.221.x:8082/voice-fccf8f7dc247430cbef35b441ad2bf3e.mp3"}}

**============这里往下都没读了**

2024-03-18 23:21:49,152 - DEBUG - [Dkey=24dcc3d0c644]: Recording Id: 4, Order: 4 Content: 成功过河后，闪电感到非常兴奋，它知道自己找到了一个聪明的方法。它继续沿着小路奔跑，很快就看到了树林的尽头。当它走出树林，阳光再次洒在它的身上，它感到一股暖流流过全身。
2024-03-18 23:21:49,153 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-03-18 23:21:49,487 - DEBUG - Received /user/folotoy/24dcc3d0c644/thing/command/callAck: message data: {'msgId': 18, 'identifier': 'audioplay', 'result': 1}
2024-03-18 23:21:49,487 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d0c644']}
2024-03-18 23:21:51,381 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 200 None
2024-03-18 23:22:00,869 - DEBUG - TTS(aliyun-tts) request time cost: 14.95s
2024-03-18 23:22:00,871 - DEBUG - Publish topic: /user/folotoy/24dcc3d0c644/thing/command/call, msg: {"msgId": 19, "identifier": "audioplay", "inputParams": {"recordingId": 4, "order": 3, "url": "http://124.221.x:8082/voice-77e8f6d1687c4830a874aefe1430a221.mp3"}}
2024-03-18 23:22:00,871 - DEBUG - [Dkey=24dcc3d0c644]: Recording Id: 4, Order: 5 Content: 在草原的另一边，闪电看到了一片开阔的地带，那里有一群羚羊在奔跑。它们看起来也在进行一场赛跑。闪电加快了速度，它的心跳加速，因为它知道比赛的终点就在前方。

就在这时，闪电注意到了一只小羚羊落在了后面，看起来它迷路了，而且很害怕。闪电停下了脚步，它面临着一个选择：是继续比赛，争取成为最快的动物，还是停下来帮助这只小羚羊。
2024-03-18 23:22:00,873 - DEBUG - Starting new HTTPS connection (1): nls-gateway-cn-shanghai.aliyuncs.com:443
2024-03-18 23:22:01,119 - DEBUG - Received /user/folotoy/24dcc3d0c644/thing/command/callAck: message data: {'msgId': 19, 'identifier': 'audioplay', 'result': 1}
2024-03-18 23:22:01,119 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['24dcc3d0c644']}
2024-03-18 23:22:02,267 - DEBUG - https://nls-gateway-cn-shanghai.aliyuncs.com:443 "POST /stream/v1/tts HTTP/1.1" 200 None
2024-03-18 23:22:40,529 - DEBUG - TTS(aliyun-tts) request time cost: 51.38s
2024-03-18 23:22:40,530 - DEBUG - Publish topic: /user/folotoy/24dcc3d0c644/thing/command/call, msg: {"msgId": 20, "identifier": "audioplay", "inputParams": {"recordingId": 4, "order": 4, "url": "http://124.221.x:8082/voice-0d61e2ceaa2d405580a7053d5a97c453.mp3"}}
2024-03-18 23:22:40,531 - DEBUG - [Dkey=24dcc3d0c644]: Recording Id: 4, Order: 6 Content: 
```

# 客户端日志
```
八爪鱼日志，
ProductKey: folotoy
HardwareVersion: 0.8.1.3
LampVersion: 1.1

layCommand, recordingId:3, order:2, url:http://124.221.x:8082/voice-30abf47648a44384b78ac1b4c464c355.mp3

I: need to play order: 2
I: About to play the following audio command:
I: Now to play order: 2
I: audio url:http://124.221.x:8082/voice-30abf47648a44384b78ac1b4c464c355.mp3
I: success to connect to host: http://124.221.x:8082/voice-30abf47648a44384b78ac1b4c464c355.mp3
I: Current command count in queue: 0

Audio is still running or there are commands in the queue, restarting the timer.

audioPlayList is empty!
**============这里往下都没读了**

FSM=====================play_exit==================================
FSM=====================atob========================================
FSM=====================idle_enter==================================
I: [EVENT] ROBOT_IDLE
I: MQTT Message[/user/folotoy/24dcc3d0c644/thing/command/call]
{"msgId": 13, "identifier": "audioplay", "inputParams": {"recordingId": 3, "order": 3, "url": "http://124.221.x:8082/voice-ba51926c81674bb59982a5334c720e1f.mp3"}}
I: Insert audioPlayCommand, recordingId:3, order:3, url:http://124.221.x:8082/voice-ba51926c81674bb59982a5334c720e1f.mp3

I: MQTT Message[/user/folotoy/24dcc3d0c644/thing/command/call]
{"msgId": 14, "identifier": "audioplay", "inputParams": {"recordingId": 3, "order": 4, "url": "http://124.221.x:8082/voice-90753867e00b44ea83000629033690a9.mp3"}}
I: Insert audioPlayCommand, recordingId:3, order:4, url:http://124.221.x:8082/voice-90753867e00b44ea83000629033690a9.mp3
I: MQTT Message[/user/folotoy/24dcc3d0c644/thing/command/call]
{"msgId": 15, "identifier": "audioplay_cmd", "inputParams": {"recordingId": 3, "total": 5}}
I: MQTT Message[/user/folotoy/24dcc3d0c644/thing/command/call]
{"msgId": 16, "identifier": "audioplay", "inputParams": {"recordingId": 3, "order": 5, "url": "http://124.221.x:8082/voice-d3228de35cab452799772a93614b0e3f.mp3"}}
I: Insert audioPlayCommand, recordingId:3, order:5, url:http://124.221.x:8082/voice-d3228de35cab452799772a93614b0e3f.mp3
```

**mp3链接直接打开 可以正常播放。**

**Comment by lewangdev** [comment]
在播放队列为空的时候，如果30s内没有收到总数或者新的url，就会进入 idle 状态，目前这个设置不能修改，如果2句之间间隔高达30s，体验也会很差，除了网速慢这种情况以外，我们还不能确定为什么会这样。

**Comment by Bossjava** [comment]
我看不到代码，只能猜。 客户端日志也没有时间线。 

可以不要把问题推给网速慢吗？ 例如打个dev包来找下问题呢？

**Comment by Bossjava** [comment]
> 在播放队列为空的时候，如果30s内没有收到总数或者新的url，就会进入 idle 状态，目前这个设置不能修改，如果2句之间间隔高达30s，体验也会很差，除了网速慢这种情况以外，我们还不能确定为什么会这样。

这个两句之间的间隔是怎么定义的？  你看我上面回复的内容，我对LOG里记录的时间是持有疑问的。

> “这个128s是从什么时候开始计算的？ 这肯定不是TTS 的 request time。”

网速快慢又要如何定义呢？  我现在配置是
云端：腾讯云上海50M
TTS/STT：阿里云ASR/TTS
客户端：中国电信1000M/中国移动1000M

是哪一端的速度拖了后腿呢？

**Comment by tanaer** [comment]
> 在播放队列为空的时候，如果30s内没有收到总数或者新的url，就会进入 idle 状态，目前这个设置不能修改，如果2句之间间隔高达30s，体验也会很差，除了网速慢这种情况以外，我们还不能确定为什么会这样。


这个两句之间的间隔是怎么定义的？ 你看我上面回复的内容，我对LOG里记录的时间是有疑问的。

“这个128s是从什么时候开始计算的？ 这肯定不是TTS 的 request time。”

网速快慢又要如何定义呢？ 我要如何排查呢？ **我能看到的是 上段话读完 的时候 服务端实际已经生成了后面好几段内容了。**

我现在配置是
云端：腾讯云上海50M
TTS/STT：阿里云ASR/TTS
客户端：中国电信1000M/中国移动1000M

是哪一端的速度拖了后腿呢？

**Comment by lewangdev** [comment]
128s就是requests时间的，这点没有问题，日志没有标识出具体是哪一个请求。一个句子会根据标点符号分成多个子句子，然后多个请求同时发出去，另外阿里云免费的账号有并发的限制，docker-compose.yml 里面的 VOICE_EXECUTOR_MAX_WORKERS 要设置为与quota一致，否则请求可能会被延迟。

玩具端有一个播放队列，在没有收到一共多少句消息的情况下，每次播完会有个5s的timeout，这个 play_timeout 还不能单独设置，稍候我发一个单独的版本给你。

**Comment by tanaer** [comment]
我又发现一个神奇的事情。客户端触发了 ROBOT_THINK， 服务端没反应。   

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/3828685/7b49d475-116a-426b-84f3-ef6dfcaed81d)


下面这张图是上一次触发这个问题的日志截图，我一共进行了3次录音，每一次我都说的“给我讲一个猎豹的故事”， 第3次服务端响应了，直接把三段语音一起识别返回了。 

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/3828685/1ad7acd6-3b75-43d7-81de-d82aa9aea8de)

**Comment by lewangdev** [comment]
感谢非常深入和细致的测试。♥️

服务是并发处理的，一起返回时会带有每条对话的语音id

**Comment by tanaer** [comment]
> 感谢非常深入和细致的测试。♥️
> 
> 服务是并发处理的，一起返回时会带有每条对话的语音id

我想问一下，为什么会生成了audio 没发呢？还是发了没收到？还是断网了？ 是因为什么原因，我在log里看不出来

I: record end button pressed
FSM=====================record_exit==================================
[734729][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
[I] AnalogAudio.h : 64 - virtual void audio_tools::AnalogAudioStream::end()
[I] AnalogAudioESP32.h : 137 - end
FSM=====================atob========================================
FSM=====================wait_enter==================================
I: [EVENT] ROBOT_THINK
I: local audio url:/recordover.mp3
I: local audio change:0

**Comment by lewangdev** [comment]
当然，再等下

**Comment by lewangdev** [comment]
试试我们的测试服务器，看看是否正常，固件正在修改，好了会马上发到这里：

地址：47.116.13.134
端口：1883

**Comment by tanaer** [comment]
> 试试我们的测试服务器，看看是否正常，固件正在修改，好了会马上发到这里：
> 
> 地址：47.116.13.134 端口：1883

我使用了这台服务器，并让他讲了一个故事，当我追问第二次的时候（第一次追问可以，但是云端似乎设置了不保留上下文） ，好像audio就发不出去了。

> FSM=====================record_exit==================================
> [304536][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] AnalogAudio.h : 64 - virtual void audio_tools::AnalogAudioStream::end()
> [I] AnalogAudioESP32.h : 137 - end
> FSM=====================atob========================================
> FSM=====================wait_enter==================================
> I: [EVENT] ROBOT_THINK
> I: local audio url:/recordover.mp3
> I: local audio change:0

> 
> Timeout for 30 seconds!
> FSM=====================wait_exit==================================
> FSM=====================atob========================================
> FSM=====================idle_enter==================================
> I: [EVENT] ROBOT_IDLE
> 
> I: Try to connect to MQTT Broker ...
> 
> I: [EVENT] ROBOT_CONNECT_MQTT_FAILURE
> I: Failed to connect to MQTT Broker!
> I: MQTT Error Code: -2, it means:
> I: Connect failed


这是服务器关了吗？

**Comment by lewangdev** [comment]
上面的日志能发一下吗？是不是Wi-Fi断了。服务器是一直开着的

**Comment by tanaer** [comment]
> 上面的日志能发一下吗？是不是Wi-Fi断了。服务器是一直开着的

玩具的灯绿色闪一会 就停留在白色常亮了

日志我只能看到这些，上面的刷没了

> [399231][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399248][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399280][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399296][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399328][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399344][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399360][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399376][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399393][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [399409][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops

> [302956][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [303006][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> [303021][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> I: record end button pressed
> FSM=====================record_exit==================================
> [303037][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> [I] AnalogAudio.h : 64 - virtual void audio_tools::AnalogAudioStream::end()
> [I] AnalogAudioESP32.h : 137 - end
> FSM=====================atob========================================
> FSM=====================wait_enter==================================
> I: [EVENT] ROBOT_THINK
> I: local audio url:/recordover.mp3
> I: local audio change:0
> 
> Timeout for 30 seconds!
> FSM=====================wait_exit==================================
> FSM=====================atob========================================
> FSM=====================idle_enter==================================
> I: [EVENT] ROBOT_IDLE
>

**Comment by lewangdev** [comment]
把 folotoy-octopus-24.12.3.27-beta.bin.zip 解压成bin文件之后再通过 tool.folotoy.com 刷入固件

刷固件说明：https://docs.folotoy.com/zh/docs/web-tool

固件下载：
[folotoy-octopus-24.12.3.27-beta.bin.zip](https://github.com/FoloToy/folotoy-server-self-hosting/files/14666442/folotoy-octopus-24.12.3.27-beta.bin.zip)

**Comment by lewangdev** [comment]
> > 上面的日志能发一下吗？是不是Wi-Fi断了。服务器是一直开着的
> 
> 玩具的灯绿色闪一会 就停留在白色常亮了
> 
> 日志我只能看到这些，上面的刷没了。 **顺便请问一下，这个TTS是哪家的？质量挺不错的**
> 
> > [399231][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399248][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399280][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399296][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399328][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399344][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399360][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399376][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399393][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [399409][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> 
> > [302956][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [303006][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > [303021][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 1024 -> 1024 bytes - in 1 hops
> > I: record end button pressed
> > FSM=====================record_exit==================================
> > [303037][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
> > [I] AnalogAudio.h : 64 - virtual void audio_tools::AnalogAudioStream::end()
> > [I] AnalogAudioESP32.h : 137 - end
> > FSM=====================atob========================================
> > FSM=====================wait_enter==================================
> > I: [EVENT] ROBOT_THINK
> > I: local audio url:/recordover.mp3
> > I: local audio change:0
> > Timeout for 30 seconds!
> > FSM=====================wait_exit==================================
> > FSM=====================atob========================================
> > FSM=====================idle_enter==================================
> > I: [EVENT] ROBOT_IDLE

感觉像Wi-Fi断了，板子是2.4G的Wi-Fi，板载天线，也可能会有2.4信号的干扰导致这样的现象。tts 用的是阿里云免费的。

这是灯色的说明：https://docs.folotoy.com/zh/docs/faq
<img width="991" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/c2380316-908c-465e-ae36-6a905a66f7c1">

**Comment by tanaer** [comment]
> 把 folotoy-octopus-24.12.3.27-beta.bin.zip 解压成bin文件之后再通过 tool.folotoy.com 刷入固件
> 
> 刷固件说明：https://docs.folotoy.com/zh/docs/web-tool
> 
> 固件下载： [folotoy-octopus-24.12.3.27-beta.bin.zip](https://github.com/FoloToy/folotoy-server-self-hosting/files/14666442/folotoy-octopus-24.12.3.27-beta.bin.zip)

这个固件暂时没有遇到上述问题，很流畅！
