### ISSUE TITLE
云端开场白缓存设计的建议

### ISSUE THREAD

**Issue by tanaer** [FoloToy/folotoy-server-self-hosting#138]
nothing

**Comment by lewangdev** [comment]
感谢反馈🤝

**Comment by lewangdev** [comment]
开场白语音不是通过文字进行缓存的，因为还有音色等配置，现在只按照角色进行了缓存。

目前的实现是一个临时的设计，因为还没有一个配置页面来设置开场白，后续会把设备开场白这个设置单独出来放在设置部分，所有的配置和文件都会通过数据库保存下来。

另外临时的解决方案，准备把开场白的语音的文件名单独做一下区分
