### ISSUE TITLE
连接自建DIFY，当需要联网搜索的问题会超时

### ISSUE THREAD

**Issue by limfoo** [FoloToy/folotoy-server-self-hosting#146]
请问下下面这种情况怎么解决，谢谢。
连接自建dify，当问到需要联网查询的问题会超时，在dify的日志看，其实是有对话记录的。

docker logs：
folotoy-1  | 2024-04-06 14:40:56,466 - DEBUG - LLM TYPE is dify
folotoy-1  | 2024-04-06 14:40:56,467 - DEBUG - Request to DIFY: https://api-ask.fulin.io/v1/chat-messages, payload={'inputs': {}, 'user': '24d7eb73654c', 'query': '什么是硬件密钥', 'conversation_id': '', 'response_mode': 'streaming'}
folotoy-1  | 2024-04-06 14:40:56,467 - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
folotoy-1  | 2024-04-06 14:40:56,468 - DEBUG - load_verify_locations cafile='/usr/local/lib/python3.11/site-packages/certifi/cacert.pem'
folotoy-1  | 2024-04-06 14:40:56,479 - DEBUG - connect_tcp.started host='api-ask.fulin.io' port=443 local_address=None timeout=5.0 socket_options=None
folotoy-1  | 2024-04-06 14:40:56,486 - DEBUG - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0xffffa1594f90>
folotoy-1  | 2024-04-06 14:40:56,486 - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0xffffa1588320> server_hostname='api-ask.fulin.io' timeout=5.0
folotoy-1  | 2024-04-06 14:40:56,660 - DEBUG - start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0xffffa1594f50>
folotoy-1  | 2024-04-06 14:40:56,661 - DEBUG - send_request_headers.started request=<Request [b'POST']>
folotoy-1  | 2024-04-06 14:40:56,661 - DEBUG - send_request_headers.complete
folotoy-1  | 2024-04-06 14:40:56,661 - DEBUG - send_request_body.started request=<Request [b'POST']>
folotoy-1  | 2024-04-06 14:40:56,661 - DEBUG - send_request_body.complete
folotoy-1  | 2024-04-06 14:40:56,661 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
folotoy-1  | 2024-04-06 14:41:01,669 - DEBUG - receive_response_headers.failed exception=ReadTimeout(TimeoutError('The read operation timed out'))
folotoy-1  | 2024-04-06 14:41:01,670 - DEBUG - response_closed.started
folotoy-1  | 2024-04-06 14:41:01,670 - DEBUG - response_closed.complete
folotoy-1  | 2024-04-06 14:41:01,670 - **WARNING - Request dify failed: The read operation timed out, data: {'inputs': {}, 'user': '24d7eb73654c', 'query': '什么是硬件密钥', 'conversation_id': '', 'response_mode': 'streaming'}**
folotoy-1  | 2024-04-06 14:41:01,671 - DEBUG - ChatCompletion request time cost: 5.20s

**Comment by lewangdev** [comment]
现在默认的超时时间是5s，目前还不能单独调整，下一版会添加自定义的timeout

**Comment by limfoo** [comment]
好的 谢谢

**Comment by lewangdev** [comment]
我先发个测试版镜像出来，在 yml 里面添加一个变量

```
HTTPX_TIMEOUT: 20
```

**Comment by lewangdev** [comment]
在 docker-compose.yml 使用这个tag：`24.14.6.2-beta`

<img width="494" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/3bbdd73b-b52b-49ff-a6e1-c3a167055c8e">


在 docker-compose.yml 中添加以下环境变量来使用


```yml
HTTPX_TIMEOUT: 20
```

**Comment by limfoo** [comment]
好多了，但是有的回话返回的不完全。但是现在有新问题，仙人掌 长按网络键无法重置网络了，救命😂

**Comment by lewangdev** [comment]
有没有什么提示？方便发一下服务器的日志吗

**Comment by limfoo** [comment]
谢谢回复，解决了。感觉是电量不足导致的，需要在外接电源或充好电后，连接webtool重启。
