### ISSUE TITLE
自己部署服务器 Timeout for 30 seconds

### ISSUE THREAD

**Issue by HuDaQian** [FoloToy/folotoy-server-self-hosting#158]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/15866222/27be464a-65dc-4dae-ac17-e66972441df2)

日志里看着是有录音，但是服务器日志里没有上传的类似字样比如 DEBUG - Received frame type: b'\x01'

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/15866222/b17da5e2-8d97-42e1-b406-99c6533f7582)

**Comment by HuDaQian** [comment]
8085的UDP端口是开了的

**Comment by lewangdev** [comment]
speesh server host 配置错了，只需要填ip，不要带http://

**Comment by lewangdev** [comment]
在docker-compose.yml里面改一下，然后重建容器，不是重启

**Comment by HuDaQian** [comment]
谢谢，两个域名删去协议之后通了。
