### ISSUE TITLE
发送语音成功，但无法交流。具体如下

### ISSUE THREAD

**Issue by sandycs-protoss** [FoloToy/folotoy-server-self-hosting#16]
1、配置
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/06b0a380-e25f-4618-97ec-daf72258734e)
2、我的AZURE和role.json（经过测试第三个是role就是火火兔选择的）
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/4ceee6b3-2a91-4876-9fe9-4bbfd4ae9d3b)
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/2581aab5-d938-4ebc-9c83-3d0699851db6)
3、目前报错信息
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/da4162dc-939b-447a-bc70-c4b0e93b2f4d)
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/56ab4177-c6e0-42a8-b46c-ff3575c1f9c2)

**Comment by lewangdev** [comment]
注意配置 AZURE_OPENAI_VERSION: "2023-05-15"，要添加引号

https://github.com/FoloToy/folotoy-server-self-hosting/issues/8#issuecomment-1732561310
