### ISSUE TITLE
调用tts成功，但是无法播放录音文件，看日志是文件目录获取不对，辛苦大佬帮忙看一下

### ISSUE THREAD

**Issue by Mrlzj91** [FoloToy/folotoy-server-self-hosting#160]
`2024/05/20 03:34:52 [error] 22#22: *74 open() "/usr/share/nginx/html/:8082/voice-bb109540f2ec467584a03c37da06291c.mp3" failed (2: No such file or directory), client: 36.112.197.0, server: localhost, request: "GET /:8082/voice-bb109540f2ec467584a03c37da06291c.mp3 HTTP/1.1", host: ""
nginx_1    | 36.112.197.0 - - [20/May/2024:03:34:52 +0000] "GET /:8082/voice-bb109540f2ec467584a03c37da06291c.mp3 HTTP/1.1" 404 153 "-" "-" "-"
folotoy_1  | 2024-05-20 11:35:00,859 - DEBUG - Received /user/folotoy/24d7eb7369d4/thing/event/post: message data: {'msgId': 0, 'identifier': 'login', 'outParams': {'role': 1}}
folotoy_1  | 2024-05-20 11:35:00,859 - DEBUG - Publish topic: /user/folotoy/24d7eb7369d4/thing/command/call, msg: {"msgId": 0, "identifier": "updatetoken", "inputParams": {"token": ""}}`

**Comment by SHLcy** [comment]
提供docker-compose.yml和roles.json的截图，注意给关键的key打码

**Comment by Mrlzj91** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/32788717/778d562f-6f3c-4ccb-bc3f-c7d37a72b7a9)
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/32788717/873a9f7d-f539-4a90-b96f-cdfae16058ef)

**Comment by SHLcy** [comment]
AUDIO_DOWNLOAD_URL: http://your_vps_ip:8082
多了‘/’

**Comment by Mrlzj91** [comment]
好的  感谢大佬，已经可以正常播放了。
