### ISSUE TITLE
How to enable cloudflare STT

### ISSUE THREAD

**Issue by nsu700** [FoloToy/folotoy-server-self-hosting#183]
https://github.com/FoloToy/folotoy-server-self-hosting/blob/d06606ee37d72b8c832b60c436f33c8b6afcbd1f/docker-compose.yml#L44

What is the option to enable cloudflare STT please

**Comment by lewangdev** [comment]
https://docs.folotoy.com/zh/docs/configuration/stt/cf-workers-ai-asr
