### ISSUE TITLE
客户端播放音频url过长时候会自动截断

### ISSUE THREAD

**Issue by xioxu** [FoloToy/folotoy-server-self-hosting#184]
我post的这个url从日志来看是客户端接收成功了，但是在播放的时候会被自动截断.
日志详细：
I: MQTT Message[/user/folotoy/ec64c98edd04/thing/command/call]
{"msgId": 4, "identifier": "iwantplay", "inputParams": {"url": "http://m701.music.126.net/20240610223234/152df3f21ecb4873fdbcac7b9e95f139/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/33406127483/7005/a2f0/bf61/df55337f571bafb19b94975cb2a5acc5.mp3"}}
I: now to play url:http://m701.music.126.net/20240610223234/152df3f21ecb4873fdbcac7b9e95f139/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/33406127483/7005/a2f0/bf61/df55337f571bafb19b94975cb2a5acc5.mp3
I: play character audio url:http://m701.music.126.net/20240610223234/152df3f21ecb4873fdbcac7b9e95f139/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/33406127483/7005/a2fd)@?
I: success to connect to host: http://m701.music.126.net/20240610223234/152df3f21ecb4873fdbcac7b9e95f139/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/33406127483/7005/a2fd)@?

**Comment by xioxu** [comment]
建议至少2083字符， 各种浏览器对url的长度限制如下：
    IE：对URL的最大限制为2083个字符，若超出这个数字，提交按钮没有任何反应。
    
    Firefox：对Firefox浏览器URL的长度限制为：65536个字符。
    
    Safari：URL最大长度限制为80000个字符。
    
    Opera：URL最大长度限制为190000个字符。
    
    Google(chrome)：URL最大长度限制为8182个字符。

**Comment by lewangdev** [comment]
> 建议至少2083字符， 各种浏览器对url的长度限制如下：
> 
>     IE：对URL的最大限制为2083个字符，若超出这个数字，提交按钮没有任何反应。
> 
>     
> 
>     Firefox：对Firefox浏览器URL的长度限制为：65536个字符。
> 
>     
> 
>     Safari：URL最大长度限制为80000个字符。
> 
>     
> 
>     Opera：URL最大长度限制为190000个字符。
> 
>     
> 
>     Google(chrome)：URL最大长度限制为8182个字符。

无法支持这么长，硬件资源有限

**Comment by xioxu** [comment]
好的  谢谢

**Comment by lewangdev** [comment]
> 好的  谢谢

下一版本我们尽量加大一下长度
