### ISSUE TITLE
火火兔使用微软azure的openAI 报错问题 

### ISSUE THREAD

**Issue by fyunpeng** [FoloToy/folotoy-server-self-hosting#21]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/18390748/29aede3c-b420-45c6-adac-5c8bbe5041d9)
前提是修改过docker-compose.yml文件的 1， 去掉#    OPENAI_OPENAI_TYPE: azure 2，roles.json 文件的 model 修改过

**Comment by fyunpeng** [comment]
本地py程序 这几个参数使用微软azure的openAI 是没有问题

**Comment by fyunpeng** [comment]
roles.json 文件"6": {
    "model": "chatgpt4",  （修改）
    "start_text": "你好，我是台湾兔，请问有什么我可以帮助你的吗？",

**Comment by lewangdev** [comment]
azure 的OpenAI接口可能返回的内容发生了变化，等我测试看一下

**Comment by fyunpeng** [comment]
py文件测试结果 直接用 微软 azure key：1， openai.api_key = '3198048b601axxxx33' 开头
 参数是  response = openai.ChatCompletion.create(
        engine="openaigpt4chat", # engine = "deployment_name",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": question},
        ]
    ) 
第二种 用自己配的oneAPI 微软openAI 分配的api  2，openai.api_key = 'sk-qP13lV2TKEctyQXxxx' 开头
 参数是response = openai.ChatCompletion.create(
    model="openaigpt4chat",
    messages=[
      {"role": "system", "content": "You are a helpful assistant."},
      {"role": "user", "content": message}
    ]
  )  这两种 key的形式不一样 参数 不一样都能成功

**Comment by lewangdev** [comment]
修改一下 docker-compose.yml 里面的参数：
把
```
AZURE_OPENAI_VERSION: 2023-07-01-preview
```
改为

```
AZURE_OPENAI_VERSION: "2023-05-15"
```

Azure支持的所有的版本可以在这里查询，尽量不要使用带 preview的版本：

https://learn.microsoft.com/zh-cn/azure/ai-services/openai/reference#completions

<img width="366" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/910fad39-8884-44d6-8712-589fb8cc09d2">

**Comment by fyunpeng** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/18390748/e3158c32-b9bb-46a0-a2a2-c7f7b2bd5de8)
修改日期后
