### ISSUE TITLE
开启Azure的Openai时无法输出声音（不开时可以）

### ISSUE THREAD

**Issue by V0zape5f** [FoloToy/folotoy-server-self-hosting#22]
配置：
#OPENAI_API_BASE: https://xxx.com/v1
      OPENAI_OPENAI_KEY: sk-JKObbbbbbbb3g3eraZT3BlbkFJpF1mepNltkgWNe0nEtzD

      OPENAI_OPENAI_TYPE: azure
      AZURE_OPENAI_KEY: d16407ac7bbbbbba9870101ec10f7bef
      AZURE_OPENAI_ENDPOINT: https://huohbbbbbbbbbbre.openai.azure.com/
      AZURE_OPENAI_VERSION: 2023-05-15

      AZURE_TTS_KEY: 58567013cbc14b7bbbbbbb19ebbfda1e
      AZURE_TTS_SERVICE_REGION: eastasia

日志输出如下错误：
folotoy-server-self-hosting-folotoy-1  | 2023-10-05 07:33:38,640 - ThreadPoolExecutor-0_0 - thread.py(58) - INFO - Transcribed:爸爸的爸爸叫什么?
folotoy-server-self-hosting-folotoy-1  | 2023-10-05 07:33:39,081 - ThreadPoolExecutor-0_0 - util.py(67) - INFO - error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
folotoy-server-self-hosting-folotoy-1  | 2023-10-05 07:33:39,083 - ThreadPoolExecutor-0_0 - thread.py(58) - ERROR - record error: Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/speech_server.py", line 188, in core.speech_server.SpeechServer.write_wav
folotoy-server-self-hosting-folotoy-1  |   File "sdk/chat.py", line 18, in sdk.chat.ChatSdk.chat
folotoy-server-self-hosting-folotoy-1  |   File "sdk/chat.py", line 35, in sdk.chat.ChatSdk.openai_chat
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
folotoy-server-self-hosting-folotoy-1  |     return super().create(*args, **kwargs)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
folotoy-server-self-hosting-folotoy-1  |     response, _, api_key = requestor.request(
folotoy-server-self-hosting-folotoy-1  |                            ^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
folotoy-server-self-hosting-folotoy-1  |     resp, got_stream = self._interpret_response(result, stream)
folotoy-server-self-hosting-folotoy-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
folotoy-server-self-hosting-folotoy-1  |     self._interpret_response_line(
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
folotoy-server-self-hosting-folotoy-1  |     raise self.handle_error_response(
folotoy-server-self-hosting-folotoy-1  | openai.error.InvalidRequestError: Resource not found
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/speech_server.py", line 188, in core.speech_server.SpeechServer.write_wav
folotoy-server-self-hosting-folotoy-1  |   File "sdk/chat.py", line 18, in sdk.chat.ChatSdk.chat
folotoy-server-self-hosting-folotoy-1  |   File "sdk/chat.py", line 35, in sdk.chat.ChatSdk.openai_chat
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
folotoy-server-self-hosting-folotoy-1  |     return super().create(*args, **kwargs)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
folotoy-server-self-hosting-folotoy-1  |     response, _, api_key = requestor.request(
folotoy-server-self-hosting-folotoy-1  |                            ^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
folotoy-server-self-hosting-folotoy-1  |     resp, got_stream = self._interpret_response(result, stream)
folotoy-server-self-hosting-folotoy-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
folotoy-server-self-hosting-folotoy-1  |     self._interpret_response_line(
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
folotoy-server-self-hosting-folotoy-1  |     raise self.handle_error_response(
folotoy-server-self-hosting-folotoy-1  | openai.error.InvalidRequestError: Resource not found

**Comment by lewangdev** [comment]
引号不能少

AZURE_OPENAI_VERSION: "2023-05-15"
