### ISSUE TITLE
不支持 minimax T2A  V2 的API，只能使用老版本接口，

### ISSUE THREAD

**Issue by leegang** [FoloToy/folotoy-server-self-hosting#225]
不支持 minimax T2A  V2 的API，只能使用老版本接口
这样就不能使用 speech-1-turbo 这里速度较快的新模型。但对这个玩具而言，速度又是个关键问题

麻烦予以支持
谢谢

**Comment by lewangdev** [comment]
感谢反馈。@x454211277 下一版请支持

**Comment by x454211277** [comment]
ok

**Comment by x454211277** [comment]
https://docs.folotoy.com/zh/docs/configuration/tts/minimax-tts   可以参考这里，将version改为T2A_V2

**Comment by leegang** [comment]
ok. 解决了

**Comment by x454211277** [comment]
https://platform.minimaxi.com/document/T2A%20V2
![Image](https://github.com/user-attachments/assets/6de093af-68ad-40fa-a303-681bf6088858)
是https://api.minimax.chat/v1
要配置单个角色只改roles.json

**Comment by dd28778131** [comment]
我是在maximax.io看文档的, 和你的有一点出入

![Image](https://github.com/user-attachments/assets/dc3e1884-4120-4122-876f-9f38b89470d8)

应该是国际版和国内版的一点差异吧, 是两个不同的API地址, 我再试试吧

![Image](https://github.com/user-attachments/assets/22693c62-ba5d-4706-81ff-88f37e5690fc)

**Comment by dd28778131** [comment]
@x454211277 
奇怪, 1号角色的提示音仍然是之前azure-stt 的声音, 没有重新下载maximax的新提示音
附上roles.json 和server log 给你做参考

[roles.json](https://github.com/user-attachments/files/19166816/roles.json)

[server_log.log](https://github.com/user-attachments/files/19166820/server_log.log)

```
    "1": {
      "start_text": "你好，我係兔兔姐姐，請問有咩我可以幫倒你嗎？",
      "prompt": "你扮演一個孩子的小伙伴，性格和善，說話活潑可愛，對孩子充滿愛心，經常贊賞和鼓勵孩子，用5歲孩子容易理解語言提供有趣和創新的回答，每次回復根據聊天主題詢問她的看法以激發她的思考和好奇心。回答中不要加入任何表情, 動作描述或顏文字",
      "max_message_count": 20,
      "temperature": 0.7,
      "max_tokens": 1500,
      "top_p": 0.95,
      "frequency_penalty": 0,
      "presence_penalty": 0,
      "stt_config": {
       "language": "zh-HK"
      },
      "tts_type": "minimax-tts",
      "tts_config": {
        "api_base": "https://api.minimaxi.chat/v1",
        "group_id": "12345678",
        "version": "t2a_v2",
        "key": "XXXXXX",
        "model": "speech-01-turbo",
        "speed": 1.0,
        "voice_id": "English_PlayfulGirl",
        "language_boost": "Chinese,Yue"
      }
    }
```

**Comment by lewangdev** [comment]
minimax的接口地址是：https://platform.minimaxi.com/document/T2A%20V2

您截图里面 maximax.io 是海外版吗？

<img width="995" alt="Image" src="https://github.com/user-attachments/assets/742a4e8f-a3a9-44ee-928a-93e5b0c981d8" />
