### ISSUE TITLE
folotoy-server镜像容器一直重启，web服务正常打开

### ISSUE THREAD

**Issue by faye25tom** [FoloToy/folotoy-server-self-hosting#27]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/44017861/303915ae-dfa6-40a4-a356-4f8bc56baa5f)

1panel面板
甲骨文云arm机器
容器日志报错：exec /usr/local/bin/python3: exec format error
这是什么问题？该如何解决？

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/44017861/cacc2387-be99-42f4-a337-6c126890a503)

**Comment by lewangdev** [comment]
目前的镜像不支持arm主机

**Comment by faye25tom** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
processor       : 0
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1


是这个吗？

**Comment by duzeng** [comment]
> 目前的镜像不支持arm主机，能把你的主机配置发一下吗？我做一个arm的镜像

只支持X86吗，我用的Raspberry Pi 也不行

**Comment by lewangdev** [comment]
不支持 ARM

**Comment by lewangdev** [comment]
最新的镜像已经支持 ARM64

**Comment by lewangdev** [comment]
我在 oracle cloud 用 arm 服务器测试过了，现在没问题了
<img width="286" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/2fd50036-3d1f-4ebe-8a1f-27e68805ab87">
