### ISSUE TITLE
火火兔连接状态 OK，按中间按键无法回复

### ISSUE THREAD

**Issue by breezezephyr** [FoloToy/folotoy-server-self-hosting#28]
环境： Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-106-generic x86_64)
docker: ➜  ~ docker --version  Docker version 24.0.6, build ed223bc

火火兔可以连上，服务端配置了（openai, azure tts）。有开机语音。长按中间按键提问后绿灯闪烁，但是没有回应。按其他按键，打印如下信息。
log:
`folotoy-server-self-hosting-emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1     | EMQX_NODE__NAME [node.name]: emqx@172.18.0.2
folotoy-server-self-hosting-emqx-1     | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1     | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1     | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1     | Listener wss:default on 0.0.0.0:8084 started.
folotoy-server-self-hosting-emqx-1     | 2023-10-15T01:53:32.411389+00:00 [warning] msg: alarm_is_activated, mfa: emqx_alarm:do_actions/3(418), message: <<"73.80% mem usage">>, name: high_system_memory_usage
folotoy-server-self-hosting-emqx-1     | Listener http:dashboard on :18083 started.
folotoy-server-self-hosting-emqx-1     | EMQX 5.3.0 is running now!
folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:53:33,388 - Thread-1 (_thread_main) - client.py(3138) - INFO - Connected to MQTT Broker(emqx:1883)!
folotoy-server-self-hosting-folotoy-1 exited with code 0
folotoy-server-self-hosting-folotoy-1 exited with code 0
folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:53:36,777 - Thread-1 (_thread_main) - client.py(3138) - INFO - Connected to MQTT Broker(emqx:1883)!
folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:53:36,778 - MainThread - main.py(5) - INFO - Speech server started(0.0.0.0:8085)
folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:53:36,778 - MainThread - main.py(5) - INFO - Listening recording data

folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:54:23,391 - Thread-1 (_thread_main) - client.py(3570) - INFO - Speech synthesis canceled: CancellationReason.Error
folotoy-server-self-hosting-folotoy-1  | 2023-10-15 01:54:23,391 - Thread-1 (_thread_main) - client.py(3570) - INFO - Error details: WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name. USP state: Sending. Received audio size: 0 bytes.`

**Comment by breezezephyr** [comment]
compose.yml 配置
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG
      ROLES_FILE_PATH: /roles.json
      #OPENAI_API_BASE: https://xxx.com/v1
      OPENAI_OPENAI_KEY: sk-ssssssssssssssssssssssssssssssssssss

      #OPENAI_OPENAI_TYPE: azure
      AZURE_OPENAI_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      AZURE_OPENAI_ENDPOINT: https://folotoy2.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-05-15"

      AZURE_TTS_KEY: ssssssssssssssssssssss
      AZURE_TTS_SERVICE_REGION: eastus2

      AUDIO_DOWNLOAD_URL: http://ssssssssssss:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy_server
      MQTT_USERNAME: sssssss
      MQTT_PASSWORD: ssssssss

      SPEECH_UDP_SERVER_HOST: ssssssssss
      SPEECH_UDP_SERVER_PORT: 8085

      #Baidu Wenyanyixin API
      #LLM_TYPE: wenyanyixin
      #WENYANYIXIN_CLIENT_ID:
      #WENYANYIXIN_SECRET:

**Comment by lewangdev** [comment]
azure的配置是否正确？日志显示是key与region不匹配

WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name. USP state: Sending.
