### ISSUE TITLE
米兔能连接上，没反应。

### ISSUE THREAD

**Issue by slwl** [FoloToy/folotoy-server-self-hosting#29]
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:39,241 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:39,253 - MainThread - main.py(5) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:41,255 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:41,256 - MainThread - main.py(5) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:43,258 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:43,259 - MainThread - main.py(5) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:45,261 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:45,262 - MainThread - main.py(5) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:47,263 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:47,265 - MainThread - main.py(5) - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-16 01:01:49,266 - MainThread - main.py(5) - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 151, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)

**Comment by lewangdev** [comment]
这个是容器启动是的日志，emqx看起来启动比较慢，如果emqx启动后，最终会打印出连接成功的信息。还有其他的日志吗？

**Comment by slwl** [comment]
olotoy-server-self-hosting-nginx-1    | 111 - - [16/Oct/2023:06:26:57 +0000] "\x16\x03\x01\11113\x03\xDA\xC4g\xA6k" 400 157 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/16 06:26:58 [error] 28#28: *5 directory index of "/usr/share/nginx/html/" is forbidden, client: 167.248.133.127, server: localhost, request: "GET / HTTP/1.1", host: "11111:8082"
folotoy-server-self-hosting-nginx-1    | 167.248.133.127 - - [16/Oct/2023:06:26:58 +0000] "GET / HTTP/1.1" 403 153 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/16 06:26:59 [error] 28#28: *6 directory index of "/usr/share/nginx/html/" is forbidden, client: 1111, server: localhost, request: "GET / HTTP/1.1", host: "1111:8082"
folotoy-server-self-hosting-nginx-1    | 1111 - - [16/Oct/2023:06:26:59 +0000] "GET / HTTP/1.1" 403 153 "-" "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)" "-"
folotoy-server-self-hosting-nginx-1    | 1111 - - [16/Oct/2023:06:26:59 +0000] "PRI * HTTP/2.0" 400 157 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/16 06:39:02 [error] 28#28: *8 directory index of "/usr/share/nginx/html/" is forbidden, client: 1111, server: localhost, request: "GET / HTTP/1.1", host: "1111:8082"
folotoy-server-self-hosting-nginx-1    | 1111 - - [16/Oct/2023:06:39:02 +0000] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
folotoy-server-self-hosting-nginx-1    | 1111 - - [16/Oct/2023:07:05:49 +0000] "\x16\x03\x01\x00\x85\x01\x001111D\x12\xA0J\x19\x00\x00 \xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/16 13:39:21 [error] 28#28: *11 directory index of "/usr/share/nginx/html/" is forbidden, client: 1111, server: localhost, request: "GET / HTTP/1.1", host: "1111"
folotoy-server-self-hosting-nginx-1    | 1111 - - [16/Oct/2023:13:39:21 +0000] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46" "-"
folotoy-server-self-hosting-nginx-1    | 2023/10/16 16:08:22 [error] 28#28: *12 directory index of "/usr/share/nginx/html/" is forbidden, client: 111, server: localhost, request: "GET / HTTP/1.1", host: "1111"
folotoy-server-self-hosting-nginx-1    | 111 - - [16/Oct/2023:16:08:22 +0000] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46" "-"
folotoy-server-self-hosting-emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1     | EMQX_NODE__NAME [node.name]: emqx@111
folotoy-server-self-hosting-emqx-1     | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1     | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1     | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1     | Listener wss:default on 0.0.0.0:8084 started.
folotoy-server-self-hosting-emqx-1     | Listener http:dashboard on :18083 started.
folotoy-server-self-hosting-emqx-1     | EMQX 5.3.0 is running now!
folotoy-server-self-hosting-emqx-1     | 2023-10-16T01:09:03.278720+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:52632, clientid: CENSYS, topic: #, ipaddr: {111}, source: file, username: undefined
folotoy-server-self-hosting-emqx-1     | 2023-10-16T07:13:15.609844+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:54692, clientid: CENSYS, topic: #, ipaddr: {111}, source: file, username: undefined
folotoy-server-self-hosting-emqx-1     | 2023-10-16T09:29:47.532562+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:34327, clientid: nmapNSJKJLFQRGOLJUAE, topic: $SYS/#, ipaddr: {111}, source: file, username: undefined
folotoy-server-self-hosting-emqx-1     | 2023-10-16T09:29:47.536006+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:34327, clientid: nmapNSJKJLFQRGOLJUAE, topic: #, ipaddr: {183,136,225,9}, source: file, username: undefined
folotoy-server-self-hosting-emqx-1     | 2023-10-16T13:59:38.393000+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:43808, clientid: CENSYS, topic: #, ipaddr: {111}, source: file, username: undefined
folotoy-server-self-hosting-emqx-1     | 2023-10-16T18:56:01.337407+00:00 [warning] msg: authorization_permission_denied, mfa: emqx_authz:authorize_non_superuser/5(420), peername: 111:35392, clientid: CENSYS, topic: #, ipaddr: {111}, source: file, username: undefined

**Comment by lewangdev** [comment]
看日志没什么问题，参考 FAQ 看下：https://github.com/FoloToy/folotoy-server-self-hosting/wiki/faq.md
