### ISSUE TITLE
增加火火兔配网IP自定义功能

### ISSUE THREAD

**Issue by yxyshcn** [FoloToy/folotoy-server-self-hosting#30]
你好，
我的folotoy服务器是装在NAS的docker上的，NAS的IP地址结尾20，但是我NAS的软路由，虚拟机IP地址结尾是22， 由于平时手机等连接虚拟机软路由可以直接在手机IP设置把网关和DNS改成软路由IP那个22结尾的地址，就能正常访问GPT了，但目前火火兔配网IP地址不能自由设置，导致最后一步无法访问GPT，能否有空优化下设置，解决我的需求，感谢大佬！

**Comment by lewangdev** [comment]
玩具的配置的过程设计是尽可能简单，自定义 ip 对于玩具来讲比较复杂，这个功能未来不会实现。
