### ISSUE TITLE
火火兔播发几句后再也不发声，后台语音已生成

### ISSUE THREAD

**Issue by gqfjob** [FoloToy/folotoy-server-self-hosting#36]
看日志，语音文件已生成，而且通过浏览器可以直接听到，火火兔不播放
 DEBUG - Speech synthesized for text [或许会有更先进的科技，让我们做很多神奇的事情，比如探索外太空或者发明超酷的玩具！你觉得未来会有什么有趣的事情呢？]
-DEBUG - Publish topic: /user/folotoy/Fxxxxxx/thing/command/call, msg: {"msgId": 14, "identifier": "audioplay", "inputParams": {"recordingId": 1, "order": 3, "url": "http://xxx.xxx.xxx.xxx:9298/voice-b6c2de17db474162908eb96a908401ff.mp3"}}
DEBUG - Received /user/folotoy/Fxxxxxx/thing/command/callAck: message data: {'msgId': 14, 'identifier': 'audioplay', 'result': 1}
DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['Fxxxxxx']} 

 上面日志说明播放命令消息已经发出到MQ了，而且火火兔应该也回复消息了，但是未听到播放声音，火火兔耳灯正常，感觉还是固件存在bug，望帮忙查明原因

**Comment by congzhong** [comment]
对，我也有这个问题，也已经更新到了最新的固件

**Comment by lewangdev** [comment]
试试这个固件：https://github.com/FoloToy/folotoy-tool/releases/tag/20231005001

**Comment by congzhong** [comment]
> 试试这个固件：https://github.com/FoloToy/folotoy-tool/releases/tag/20231005001

试了，目前会好不少，谢了

**Comment by gqfjob** [comment]
火火兔那边日志也显示接收了语音，但是就是不播放声音，日志如下

**Comment by gqfjob** [comment]
还有一个现象，就是火火兔说话时，usb连接查看后台日志，会很不稳定，时常会出现断开链接情况，是内存有问题？

**Comment by lewangdev** [comment]
已经长时间没有回复，关闭issue，如有如有需要请重新开启
