### ISSUE TITLE
可以不同的角色调用不同的模型吗？

### ISSUE THREAD

**Issue by seeyousoon** [FoloToy/folotoy-server-self-hosting#37]
ChatGPT对古诗的回答错误率很高，文心一言正确率要高一些，YAML配置中有文心一言的相关配置，有相关说明吗？可以有的角色调用GPT，有的角色调用文心一言吗？

**Comment by lewangdev** [comment]
文心一言模型现在需要使用one-api来中转使用。

可以在roles.json文件中为每一个角色配置不同的模型

**Comment by seeyousoon** [comment]
![roles](https://github.com/FoloToy/folotoy-server-self-hosting/assets/9016941/71c676a8-d4f6-453f-8425-ec253e90b9e0)
![one-api](https://github.com/FoloToy/folotoy-server-self-hosting/assets/9016941/e0112e2e-8199-464c-a105-640118ca2f28)

**Comment by lewangdev** [comment]
```
OPENAI_OPENAI_API_BASE: http://192.168.99.171:3001/v1
```

**Comment by seeyousoon** [comment]
字段改了，还是不可以，好像自定义的API没有被调用，我用Docker也部署了一个ChatGPT-Next-Web镜像，可以正常调用One-api, 抱歉，我偏小白，打扰了。
![error](https://github.com/FoloToy/folotoy-server-self-hosting/assets/9016941/ae4de414-1cb2-47d0-b6b7-4d4c59900817)
![openai](https://github.com/FoloToy/folotoy-server-self-hosting/assets/9016941/1853f6f5-d7f8-4830-9652-ac42b8ab690e)
![NEXT](https://github.com/FoloToy/folotoy-server-self-hosting/assets/9016941/d35dc2a8-cdd4-436f-91c6-1ed4f47135ce)

**Comment by lewangdev** [comment]
改完之后需要执行 sudo docker compose up -d

**Comment by lewangdev** [comment]
我也配置测了一下。

- 文心一言不能用，因为文心一言不支持system prompt。
- 讯飞的星火v2.1没问题，可以正常使用

**Comment by 2922832737C** [comment]
我已经在docker.yaml文件中配置了ElevenLabs，elevenlabs的语音ID这个怎么获取

**Comment by lewangdev** [comment]
elevenlabs  Voice ID 藏得比较深，在这里：
<img width="505" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/c96d9a9a-9e0f-4206-b69b-c24d2b14ac3f">
