### ISSUE TITLE
火火兔无法只能把话说一半，但是从后台日志看，文字已经是完整的。

### ISSUE THREAD

**Issue by congzhong** [FoloToy/folotoy-server-self-hosting#38]
建议一：改进这一点，让他说话完整。
建议二：如果在回复时再次说话，让chatgpt断开上一次的对话。或者不支持断开，让他把话说完整也行，在说完上一个问题之后不支持继续问下一个问题。
建议三：希望保留上下文的功能，可以参考当前毕竟流行的chatgpt的网页，他们至少可以保留4-8轮以上的对话，现在是不能连续对话的。

**Comment by lewangdev** [comment]
1. 可以试试这个版本的固件，下载语音的超时比较长 https://github.com/FoloToy/folotoy-tool/releases/tag/20231005001
2. 新版本固件正在修复这个问题
3. 可以参考 FAQ 进行上下文配置：https://github.com/FoloToy/folotoy-server-self-hosting/wiki/FAQ

**Comment by congzhong** [comment]
这个版本会好很多，谢谢

**Comment by congzhong** [comment]
> 1. 可以试试这个版本的固件，下载语音的超时比较长 https://github.com/FoloToy/folotoy-tool/releases/tag/20231005001
> 2. 新版本固件正在修复这个问题
> 3. 可以参考 FAQ 进行上下文配置：https://github.com/FoloToy/folotoy-server-self-hosting/wiki/FAQ

如果后续有更新，也帮忙说一下，或者在b站上发视频，或者发邮件都可以，我也会持续关注

**Comment by lekai63** [comment]
目前超时20s的配置，对于GPT-3.5的model 基本问题不大了。但对于GPT-4的model，还是断了点：后台日志文字完整，说话只能一半。

能否按角色配置超时时长呢？或者对于model配置为GPT-4的，接受更长的超时 ？
