### ISSUE TITLE
网络配置

### ISSUE THREAD

**Issue by 2922832737C** [FoloToy/folotoy-server-self-hosting#40]
本地服务器搭建好之后，网络链接成功，能够正常的聊天，但是把服务部署到公网上的话，登上18083后台，进行小兔网络连接的时候，小兔回应的时候直接断开了

**Comment by lewangdev** [comment]
参考一下  [FAQ](https://github.com/FoloToy/folotoy-server-self-hosting/wiki/FAQ)

确认以下端口是否打开，如果主机服务商有防火墙或者访问规则的设置，这些端口也需要打开。

folotoy-server-self-hosting 默认的配置 docker-compose.yml 中，使用了 1883/tcp，8082/tcp，18083/tcp，8085/udp 这几个端口：

1883/tcp : 必选, 玩具通过 MQTT(1883/tcp) 连接服务器
8082/tcp : 必选, 玩具下载开机语音流和对话语音流的 HTTP 服务端口
8085/udp : 必选, 玩具实时上传语音流的 UDP 端口
18083/tcp: 可选, EMQX 的 Web 管理后台的 HTTP 端口

**Comment by 2922832737C** [comment]
感谢，解决了，但是现在又有一个问题，就是他回答的时候断断续续的，卡顿的很厉害

**Comment by lewangdev** [comment]
刷这个固件试试：https://github.com/FoloToy/folotoy-tool/releases/tag/20231005001
