### ISSUE TITLE
docker启动后日志报错

### ISSUE THREAD

**Issue by charryshi** [FoloToy/folotoy-server-self-hosting#50]
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 159, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | TimeoutError: timed out
folotoy-server-self-hosting-folotoy-1  | 2023-10-30 08:54:13,710 - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-10-30 08:54:20,716 - ERROR - Run error: timed out
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 159, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | TimeoutError: timed out
folotoy-server-self-hosting-folotoy-1  | 2023-10-30 08:54:20,718 - INFO - Sleep 2s to reconnect

配置应该都改好了，看不到源文件所以无法排查，麻烦帮忙看看可能的问题，谢谢

**Comment by lewangdev** [comment]
发一下配置文件docker-compose.yml的内容

**Comment by charryshi** [comment]
version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883/tcp"
      - "18083:18083/tcp"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8082:80/tcp"
    volumes:
      - ./audio:/usr/share/nginx/html
  folotoy:
    image: lewangdev/folotoy-server:latest
    restart: always
    depends_on:
      emqx:
          condition: service_started
      nginx:
          condition: service_started
    ports:
      - "8085:8085/udp"
    volumes:
      - ./audio:/audio
      - ./roles.json:/roles.json
    environment:
      LOG_LEVEL: DEBUG

      ROLES_FILE_PATH: /roles.json

      # Default STT(Sound To Text) type
      # Options: [openai-whisper, azure-whisper, azure-stt]
      STT_TYPE: openai-whisper

      # OpenAI Whisper
      #OPENAI_WHISPER_API_BASE: https://one-api.xxxx.com/v1
      OPENAI_WHISPER_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      OPENAI_WHISPER_MODEL: whisper-1
      
      # Azure Whisper
      AZURE_WHISPER_API_BASE: https://xxxxx.openai.azure.com
      AZURE_WHISPER_KEY: 9afbef65bcf6487eeeeeeeeeeeeeeeeeee
      AZURE_WHISPER_DEPLOYMENT_NAME: whisper
      AZURE_WHISPER_API_VERSION: 2023-09-01-preview

      # Azure STT
      AZURE_STT_KEY: 3eba91b6143f4d3eeeeeeeeeeeeeeeeeeeeeeeee
      AZURE_STT_SERVICE_REGION: eastasia

      # Default LLM(Large Language Model) type
      # Options: [openai, azure-openai]
      LLM_TYPE: openai

      # OpenAI
      #OPENAI_OPENAI_API_BASE: https://one-api.xxx.com/v1
      OPENAI_OPENAI_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      #Azure OpenAI
      AZURE_OPENAI_KEY: ef0f2781b5a24b15baaaaaaaaaaaaaaaaaaaaaaa
      AZURE_OPENAI_ENDPOINT: https://xxxxx.openai.azure.com/
      AZURE_OPENAI_VERSION: "2023-05-15"

      #Baidu YIYAN API
      #LLM_TYPE: yiyan
      YIYAN_CLIENT_ID: xxxxxxxxxxxxxxxxxx
      YIYAN_SECRET: xxxxxxxxxxxxxxxxxxxxx

      # If your elevenlabs is a free account, keep 2 here
      VOICE_EXECUTOR_MAX_WORKERS: 2

      # Default TTS(Text to Sound) type
      # Options: [edge-tts, azure-tts, elevenlabs]
      # edge-tts is Free but slow
      TTS_TYPE: azure-tts

      # Azure TTS
      AZURE_TTS_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      AZURE_TTS_SERVICE_REGION: eastasia

      # elevenlabs
      ELEVENLABS_TTS_KEY: a920b73991e68d5c9c9aaaaaaaaaaaaaaaa
      ELEVENLABS_TTS_MODEL: eleven_multilingual_v2

      AUDIO_DOWNLOAD_URL: http://192.168.1.243:8082
      AUDIO_SAVE_PATH: /audio

      # MQTT Broker
      MQTT_BROKER_HOST: emqx
      MQTT_BROKER_PORT: 1883
      MQTT_CLIENT_ID: folotoy
      MQTT_USERNAME: folotoy
      MQTT_PASSWORD: folotoy

      SPEECH_UDP_SERVER_HOST: 192.168.1.243
      SPEECH_UDP_SERVER_PORT: 8085

**Comment by lewangdev** [comment]
配置没有问题，emqx端口是否被占用了，
？看日志可能emqx没有启动成功

**Comment by charryshi** [comment]
看端口没问题，但http连接18083超时
netstat -nap|grep 83
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      718767/docker-proxy 
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      718745/docker-proxy 
tcp6       0      0 :::1883                 :::*                    LISTEN      718775/docker-proxy 
tcp6       0      0 :::18083                :::*                    LISTEN      718752/docker-proxy 


sudo docker compose logs emqx
folotoy-server-self-hosting-emqx-1  | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1  | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1  | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-emqx-1  | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1  | EMQX_NODE__NAME [node.name]: emqx@172.18.0.3
folotoy-server-self-hosting-emqx-1  | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1  | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1  | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1  | Listener wss:default on 0.0.0.0:8084 started.
folotoy-server-self-hosting-emqx-1  | Listener http:dashboard on :18083 started.
folotoy-server-self-hosting-emqx-1  | EMQX 5.3.0 is running now!
folotoy-server-self-hosting-emqx-1  | Received terminate signal, shutting down now
folotoy-server-self-hosting-emqx-1  | Stop listener http:dashboard on :18083 successfully.
folotoy-server-self-hosting-emqx-1  | Listener ssl:default on 0.0.0.0:8883 stopped.
folotoy-server-self-hosting-emqx-1  | Listener tcp:default on 0.0.0.0:1883 stopped.
folotoy-server-self-hosting-emqx-1  | Listener ws:default on 0.0.0.0:8083 stopped.
folotoy-server-self-hosting-emqx-1  | Listener wss:default on 0.0.0.0:8084 stopped.
folotoy-server-self-hosting-emqx-1  | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1  | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1  | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-emqx-1  | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1  | EMQX_NODE__NAME [node.name]: emqx@172.18.0.3
folotoy-server-self-hosting-emqx-1  | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1  | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1  | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1  | Listener wss:default on 0.0.0.0:8084 started.
folotoy-server-self-hosting-emqx-1  | Listener http:dashboard on :18083 started.
folotoy-server-self-hosting-emqx-1  | EMQX 5.3.0 is running now!

**Comment by lewangdev** [comment]
本机的网络和docker网络是否有冲突。从日志看不出来有什么问题

**Comment by charryshi** [comment]
发现还是docker间网络问题，改了后docker间能通信，宿主机访问也正常，但同网端机器又访问不了docker上的服务，防火墙规则等都正常，宿主机上其他服务都正常iptables也没发现问题。
算了，直接改host模式免得折腾了
network_mode: host

**Comment by charryshi** [comment]
关闭issues

**Comment by lewangdev** [comment]
阿里云的主机吗？

**Comment by charryshi** [comment]
不是，自己的一台机器，阿里云的话估计类似问题就是内网IP段冲突
