### ISSUE TITLE
没有返回的语音

### ISSUE THREAD

**Issue by NovermberRain** [FoloToy/folotoy-server-self-hosting#52]
![23691698762344_ pic](https://github.com/FoloToy/folotoy-server-self-hosting/assets/66247206/930df52d-541c-43ae-a485-443e1b6bc6cd)

**Comment by NovermberRain** [comment]
用的是oneapi的中转接口，可能是没有whisper的原因，但是没办法检验

**Comment by NovermberRain** [comment]
aduio文件夹
<img width="1291" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/66247206/3a313950-e27e-4393-bca7-33cd86d16d1b">

**Comment by lewangdev** [comment]
one-api 有 whipser-1 模型吗

**Comment by NovermberRain** [comment]
<img width="795" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/66247206/bb98591d-cd38-4652-aaf4-b1cee2bcb3e5">
我用的是这个，能帮忙验证一下吗

**Comment by lewangdev** [comment]
方便把key发到我的邮箱吗：lewang.dev@gmail.com

**Comment by NovermberRain** [comment]
发您了

**Comment by lewangdev** [comment]
key 没有 whisper-1 权限
