### ISSUE TITLE
使用体验服务器，录制语音后没有反应

### ISSUE THREAD

**Issue by marvyn** [FoloToy/folotoy-server-self-hosting#58]
收到了成品火火兔，配置好 WiFi 和体验服务器的 MQTT 配置后，能收到问候语，切换角色都正常，但按中间按键发送语音后没有反应。
到 FoloToy Web Tool 界面连接串口观察到日志如下：
1.  录音后处理的 log
![微信图片_20231106005836](https://github.com/FoloToy/folotoy-server-self-hosting/assets/683256/c3044d6f-cd3e-420c-8768-2952aa47b9ea)

2. 录音后超时，进入正常状态，切换角色，能正常下载体验服务器中预置的 roles 中的问候语并播放
![微信图片_20231106005937](https://github.com/FoloToy/folotoy-server-self-hosting/assets/683256/c7125a35-3027-4fe5-9e3e-b0ac1323a7a7)

**Comment by lewangdev** [comment]
hi，发我一下你的sn，我的邮箱lewang.dev@gmail.com或者t.me/lewang，我查一下服务器日志

**Comment by lewangdev** [comment]
看日志应该是服务器回复语音超时了，体验服务器晚上的时候有时会比较慢

**Comment by lewangdev** [comment]
查了日志，服务器没有收到玩具发送的udp语音数据包

**Comment by marvyn** [comment]
那可能是体验服务器或者网络超时的原因？

**Comment by lewangdev** [comment]
应该是udp通道不通

**Comment by marvyn** [comment]
嗯，跟服务器之间还是需要比较顺畅的网络才行。
