### ISSUE TITLE
服务器报网络错误，实测无法打开管理页面，烦请指点，谢谢

### ISSUE THREAD

**Issue by antiBoson** [FoloToy/folotoy-server-self-hosting#63]
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:22,417 - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 159, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:22,418 - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:24,421 - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 159, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:24,422 - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:26,423 - ERROR - Run error: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | Traceback (most recent call last):
folotoy-server-self-hosting-folotoy-1  |   File "core/folotoy_app.py", line 159, in core.folotoy_app.FolotoyApp.start
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
folotoy-server-self-hosting-folotoy-1  |     return self.reconnect()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
folotoy-server-self-hosting-folotoy-1  |     sock = self._create_socket_connection()
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
folotoy-server-self-hosting-folotoy-1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
folotoy-server-self-hosting-folotoy-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
folotoy-server-self-hosting-folotoy-1  |     raise exceptions[0]
folotoy-server-self-hosting-folotoy-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
folotoy-server-self-hosting-folotoy-1  |     sock.connect(sa)
folotoy-server-self-hosting-folotoy-1  | ConnectionRefusedError: [Errno 111] Connection refused
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:26,424 - INFO - Sleep 2s to reconnect
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:28,427 - INFO - Connected to MQTT Broker(emqx:1883)!
folotoy-server-self-hosting-folotoy-1  | 2023-11-09 23:41:28,428 - INFO - Speech server started(0.0.0.0:8085/udp)
folotoy-server-self-hosting-emqx-1     | WARNING: Default (insecure) Erlang cookie is in use.
folotoy-server-self-hosting-emqx-1     | WARNING: Configure node.cookie in /opt/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
folotoy-server-self-hosting-emqx-1     | WARNING: NOTE: Use the same cookie for all nodes in the cluster.
folotoy-server-self-hosting-emqx-1     | EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
folotoy-server-self-hosting-emqx-1     | EMQX_NODE__NAME [node.name]: emqx@172.18.0.2
folotoy-server-self-hosting-emqx-1     | Listener ssl:default on 0.0.0.0:8883 started.
folotoy-server-self-hosting-emqx-1     | Listener tcp:default on 0.0.0.0:1883 started.
folotoy-server-self-hosting-emqx-1     | Listener ws:default on 0.0.0.0:8083 started.
folotoy-server-self-hosting-emqx-1     | Listener wss:default on 0.0.0.0:8084 started.

**Comment by lewangdev** [comment]
启动没有问题，防火墙开了吗？查看一下faq 

https://docs.folotoy.com/docs/faq#cant-connect-to-your-own-server
