### ISSUE TITLE
TTS播报只播了一句，后面的没有播

### ISSUE THREAD

**Issue by andrewChang** [FoloToy/folotoy-server-self-hosting#70]
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:20,558 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/chat/completions HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:20,559 - DEBUG - message='OpenAI API response' path=https://openai-api.magickchat.com/v1/chat/completions processing_ms=5815 request_id=6711a8f2219fb09e90867417a1fb06b9 response_code=200
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:22,222 - DEBUG - [Dkey=08d1f9c6fcac]: Recording Id: 0, Order: 1 Content: 有一只小鸟叫小嘟嘟，
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:22,223 - DEBUG - Starting new HTTPS connection (1): openai-api.magickchat.com:443
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:26,034 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:29,173 - DEBUG - TTS(openai-tts) request time cost: 6.95s
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:29,174 - DEBUG - Publish topic: **/user/folotoy/08d1f9c6fcac/thing/command/call, msg: {"msgId": 2, "identifier": "audioplay", "inputParams": {"recordingId": 0, "order": 1, "url": "http://150.158.32.245:8082/voice-6d2d4dcfda834725bfdeeeb83abfb7d5.mp3"}}**
folotoy-server-self-hosting-nginx-1    | 183.212.248.224 - - [19/Nov/2023:12:01:30 +0000] "GET /voice-6d2d4dcfda834725bfdeeeb83abfb7d5.mp3 HTTP/1.1" 200 41760 "-" "-" "-"
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:30,746 - DEBUG - Received /user/folotoy/08d1f9c6fcac/thing/command/callAck: message data: {'msgId': 2, 'identifier': 'audioplay', 'result': 1}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:30,746 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c6fcac']}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:34,664 - DEBUG - [Dkey=08d1f9c6fcac]: Recording Id: 0, Order: 2 Content: 它有一双美丽的翅膀，但不幸遇到了一次意外。
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:34,667 - DEBUG - Starting new HTTPS connection (1): openai-api.magickchat.com:443
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:35,146 - DEBUG - [Dkey=08d1f9c6fcac]: Recording Id: 0, Order: 3 Content: 一天，小嘟嘟在飞行时撞到了一棵树，它的翅膀受伤了，无法再飞翔。它感到很沮丧，但并不放弃。小嘟嘟决定用自己的时间和努力来学习其他技能。
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:35,148 - DEBUG - Starting new HTTPS connection (1): openai-api.magickchat.com:443
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:38,750 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:39,763 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:43,760 - DEBUG - TTS(openai-tts) request time cost: 9.10s
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:43,762 - DEBUG - Publish topic: /user/folotoy/08d1f9c6fcac/thing/command/call, msg: {"msgId": 3, "identifier": "audioplay", "inputParams": {"recordingId": 0, "order": 2, "url": "http://150.158.32.245:8082/voice-a40c2d1e45814acd9a9ffa011e7a1043.mp3"}}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:46,221 - DEBUG - [Dkey=08d1f9c6fcac]: Recording Id: 0, Order: 4 Content: 它学会了用脚走路、用嘴唱歌，还学会了用眼睛欣赏美丽的风景。虽然不能再飞翔，但小嘟嘟依然快乐地生活着，它发现了其他的乐趣和价值。最后，小嘟嘟成为了朋友们的鼓励和榜样，
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:46,222 - DEBUG - Starting new HTTPS connection (1): openai-api.magickchat.com:443
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:46,253 - DEBUG - Received /user/folotoy/08d1f9c6fcac/thing/command/callAck: message data: {'msgId': 3, 'identifier': 'audioplay', 'result': 1}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:46,254 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c6fcac']}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:49,297 - DEBUG - ChatCompletion request time cost: 34.87s
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:50,124 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 200 None
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:58,896 - DEBUG - TTS(openai-tts) request time cost: 23.75s
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:58,897 - DEBUG - Publish topic: /user/folotoy/08d1f9c6fcac/thing/command/call, msg: {"msgId": 4, "identifier": "audioplay", "inputParams": {"recordingId": 0, "order": 3, "url": "http://150.158.32.245:8082/voice-7444f6cf6a884523a620492d57b90224.mp3"}}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:58,897 - DEBUG - [Dkey=08d1f9c6fcac]: Recording Id: 0, Order: 5 Content: 教会了大家勇敢面对挑战，并且相信每个人都有自己独特的价值和能力。
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:01:58,899 - DEBUG - Starting new HTTPS connection (1): openai-api.magickchat.com:443
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:00,548 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 429 485
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:00,549 - WARNING - TTS(openai-tts) request failed: {
folotoy-server-self-hosting-folotoy-1  |     "error": {
folotoy-server-self-hosting-folotoy-1  |         "message": "Rate limit reached for tts-1 in organization org-YQzh6FfKI0PDtqJ3a1EzOx0k on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.",
folotoy-server-self-hosting-folotoy-1  |         "type": "requests",
folotoy-server-self-hosting-folotoy-1  |         "param": null,
folotoy-server-self-hosting-folotoy-1  |         "code": "rate_limit_exceeded"
folotoy-server-self-hosting-folotoy-1  |     }
folotoy-server-self-hosting-folotoy-1  | }
folotoy-server-self-hosting-folotoy-1  | , data: {'model': 'tts-1', 'input': '教会了大家勇敢面对挑战，并且相信每个人都有自己独特的价值和能力。', 'voice': 'nova', 'response_format': 'mp3', 'speed': 1.0}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:00,551 - DEBUG - Publish topic: /user/folotoy/08d1f9c6fcac/thing/command/call, msg: {"msgId": 5, "identifier": "audioplay_cmd", "inputParams": {"recordingId": 0, "total": 5}}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:01,783 - DEBUG - Received /user/folotoy/08d1f9c6fcac/thing/command/callAck: message data: {'msgId': 4, 'identifier': 'audioplay', 'result': 1}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:01,783 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c6fcac']}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:03,303 - DEBUG - Received /user/folotoy/08d1f9c6fcac/thing/command/callAck: message data: {'msgId': 5, 'identifier': 'audioplay_cmd', 'result': 1}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:03,303 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c6fcac']}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:15,979 - DEBUG - TTS(openai-tts) request time cost: 29.76s
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:15,980 - DEBUG - Publish topic: /user/folotoy/08d1f9c6fcac/thing/command/call, msg: {"msgId": 6, "identifier": "audioplay", "inputParams": {"recordingId": 0, "order": 4, "url": "http://150.158.32.245:8082/voice-99a2bb4e4e19471aa2cf359e4f5cf36c.mp3"}}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:18,831 - DEBUG - Received /user/folotoy/08d1f9c6fcac/thing/command/callAck: message data: {'msgId': 6, 'identifier': 'audioplay', 'result': 1}
folotoy-server-self-hosting-folotoy-1  | 2023-11-19 20:02:18,831 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['08d1f9c6fcac']}

**Comment by lewangdev** [comment]
看日志是tts超过了OpenAI的限制了

**Comment by lewangdev** [comment]
免费的账号限制是3

19 20:02:00,548 - DEBUG - https://openai-api.magickchat.com:443 "POST /v1/audio/speech HTTP/1.1" 429 485
folotoy-server-self-hosting-folotoy-1 | 2023-11-19 20:02:00,549 - WARNING - TTS(openai-tts) request failed: {
folotoy-server-self-hosting-folotoy-1 | "error": {
folotoy-server-self-hosting-folotoy-1 | "message": "Rate limit reached for tts-1 in organization org-YQzh6FfKI0PDtqJ3a1EzOx0k on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.",

**Comment by lewangdev** [comment]
请问这个参数配置是多少

VOICE_EXECUTOR_MAX_WORKERS

**Comment by andrewChang** [comment]
VOICE_EXECUTOR_MAX_WORKERS: 2
Voice task threadpool max size  这个代表什么意思啊
超过3次，至少能播出来3次的文本，只听到了一次。。。。

**Comment by lewangdev** [comment]
> VOICE_EXECUTOR_MAX_WORKERS: 2
> 
> Voice task threadpool max size  这个代表什么意思啊
> 
> 超过3次，至少能播出来3次的文本，只听到了一次。。。。
> 
> 
升级固件试试，新固件很少出现断播的情况

这个变量控制并发请求的数量的，设置为2是可以的

**Comment by andrewChang** [comment]
升级固件的链接发一下，我参照试一试发自我的手机-------- 原始邮件 --------发件人： lewang ***@***.***>日期： 2023年11月20日周一 晚上10:50收件人： FoloToy/folotoy-server-self-hosting ***@***.***>抄送： andrewChang ***@***.***>, Author ***@***.***>主    题： Re: [FoloToy/folotoy-server-self-hosting] TTS播报只播了一句，后面的没有播 (Issue #70)

VOICE_EXECUTOR_MAX_WORKERS: 2
Voice task threadpool max size  这个代表什么意思啊
超过3次，至少能播出来3次的文本，只听到了一次。。。。

升级固件试试，新固件很少出现断播的情况
这个变量控制并发请求的数量的，设置为2是可以的

**Comment by lewangdev** [comment]
https://github.com/FoloToy/folotoy-bin/releases/

**Comment by andrewChang** [comment]
固件升级好了，服务是不是也要跟着升级下？报找不到role 0角色

**Comment by lewangdev** [comment]
可以在 roles.json 里面添加一个 0 的定义或者按一下角色键切换一下
