### ISSUE TITLE
roles.json里面可不可以设置azure TTS的角色性格和说话风格？

### ISSUE THREAD

**Issue by faye25tom** [FoloToy/folotoy-server-self-hosting#74]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/44017861/ac7f69cb-e42b-43e3-8ac5-8b11887aeefe)

**Comment by lewangdev** [comment]
谢谢建议。下周发布的镜像将会支持 SSML。目前可以通过修改 docker-compose.yml 中 来体验：
```yml
  folotoy:
    image: lewangdev/folotoy-server:latest
```
为
```yml
  folotoy:
    image: lewangdev/folotoy-server:23.47.2.0-beta

```

修改完成后，执行以下命令来升级：

```sh
sudo docker compose up folotoy -d
```

可以在 tts_type 为 azure-tts 是，在 tts_config 中添加的配置如下

| 字段 | 说明 | 默认值 |
| --- | --- | --- |
| style | The voice-specific speaking style. You can express emotions like cheerfulness, empathy, and calmness. You can also optimize the voice for different scenarios like customer service, newscast, and voice assistant. If the style value is missing or invalid, the entire mstts:express-as element is ignored and the service uses the default neutral speech.  | 无，如果配置了这个字段，将会使用 ssml 来生成语音 |
| styledegree | The intensity of the speaking style. You can specify a stronger or softer style to make the speech more expressive or subdued. The range of accepted values are: 0.01 to 2 inclusive. The default value is 1, which means the predefined style intensity. The minimum unit is 0.01, which results in a slight tendency for the target style. A value of 2 results in a doubling of the default style intensity. If the style degree is missing or isn't supported for your voice, this attribute is ignored. | 默认值是1，只有设置了 style 字段才会生效 |
| role | The speaking role-play. The voice can imitate a different age and gender, but the voice name isn't changed. For example, a male voice can raise the pitch and change the intonation to imitate a female voice, but the voice name isn't be changed. If the role is missing or isn't supported for your voice, this attribute is ignored. | 无，只有设置了 style 字段才会生效 |
