### ISSUE TITLE
旋转尾巴无法调节音量

### ISSUE THREAD

**Issue by bfchengnuo** [FoloToy/folotoy-server-self-hosting#77]
使用的 folotoy-23.46.3.1 版本，音量大小是固定的吗？

**Comment by lewangdev** [comment]
不是固定的，尾巴旋钮无法调节声音大小吗

**Comment by bfchengnuo** [comment]
> 不是固定的，尾巴旋钮无法调节声音大小吗

是的，我这个是G6，开机声音就很大，旋钮没有什么效果，只有开关的作用，原因可能是什么呢

**Comment by lewangdev** [comment]
是整机还是自己组装的？如果是整机可能是旋钮有问题，需要邮寄回来查看一下

**Comment by bfchengnuo** [comment]
> 是整机还是自己组装的？如果是整机可能是旋钮有问题，需要邮寄回来查看一下

自己组装的，没拆之前是好的，所以说可能是组装的问题？

**Comment by lewangdev** [comment]
> > 是整机还是自己组装的？如果是整机可能是旋钮有问题，需要邮寄回来查看一下
> 
> 
> 
> 自己组装的，没拆之前是好的，所以说可能是组装的问题？

如果原来是好的，应该也没问题。方便看一下刷的固件版本吗？最早的板子固件声音调节不够线性，

**Comment by bfchengnuo** [comment]
> > > 是整机还是自己组装的？如果是整机可能是旋钮有问题，需要邮寄回来查看一下
> > 
> > 
> > 自己组装的，没拆之前是好的，所以说可能是组装的问题？
> 
> 如果原来是好的，应该也没问题。方便看一下刷的固件版本吗？最早的板子固件声音调节不够线性，

今天重新试了下，声音大小可以调节了，但是昨天确实是没有效果的（目前尚不清楚触发条件是什么），现在剩下的问题是开机提示音和第一句对话的音量非常大声，即使旋钮是最小还是吓我一跳，后续的回话通过旋钮调节是有效的。

这个板子是比较早买的，10 月份初的那一批吧，一直没时间搞，后续我有时间再买块板子试试看，问题先关掉；
```
G6  昨天刷入的 folotoy-23.46.3.1.bin
WiFiManager  v2.0.15-rc.1
Arduino  2.0.11
Build date  Nov 17 2023 17:01:45
```
