### ISSUE TITLE
配置好Azure和OpenAI后，报错

### ISSUE THREAD

**Issue by sandycs-protoss** [FoloToy/folotoy-server-self-hosting#8]
openai.error.InvalidRequestError: The API deployment for this resource does not exist

**Comment by sandycs-protoss** [comment]
调用的地方在这里：chat_completion = openai.ChatCompletion.create(**params)
这里报错了

**Comment by lewangdev** [comment]
提供一下配置文件和azure部署的model列表截图

**Comment by sandycs-protoss** [comment]
azure部署的model列表这个是在哪里配置的？
我应该没有配置model

**Comment by lewangdev** [comment]
<img width="499" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/006b53ff-2bf7-415a-8488-0607a365ce95">
<img width="773" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/94b3bb41-1983-4a2a-a38a-dbefc0caedc0">

**Comment by sandycs-protoss** [comment]
我的Azure配置是这样的：
我的compose文件：

OPENAI_OPENAI_TYPE: azure
AZURE_OPENAI_KEY: 我的openai 的key
AZURE_OPENAI_ENDPOINT: https://calceusopenai.openai.azure.com/
AZURE_OPENAI_VERSION: 2023-07-01-preview


"1": {
		"model": "gpt-4",
		"start_text": "你好，我是火火兔，请问有什么我可以帮助你的吗？",
		"prompt": "你是一个知识渊博，乐于助人的智能机器人,你的名字叫“火火兔”，你的任务是陪我聊天，请用简短的对话方式，用中文讲一段话，每次回答不超过50个字！",
		"max_message_count": 0,
		"temperature": 0.7,
		"max_tokens": 1024,
		"top_p": 0.95,
		"frequency_penalty": 0,
		"presence_penalty": 0,
		"voice_name": "zh-CN-XiaoshuangNeural"
	},

**Comment by lewangdev** [comment]
OPENAI_OPENAI_KEY 也要配置

**Comment by sandycs-protoss** [comment]
OPENAI_OPENAI_KEY 我也做了配置。它目前应该已经识别出我的语音，只是在回复我的时候调用出错

**Comment by lewangdev** [comment]
> OPENAI_OPENAI_KEY 我也做了配置。它目前应该已经识别出我的语音，只是在回复我的时候调用出错

发完整的配置，如果只有部分配置，是无法定位问题的

**Comment by lewangdev** [comment]
这个截图有吗？
<img width="773" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/d245b130-fa5c-4534-ae5a-5b00d25eb6f1">

**Comment by sandycs-protoss** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/a8b896c2-ba48-4563-bd9a-0326ca293ea8)
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/110161224/1db3679c-84d8-4135-8dc6-60b2a35bcbbe)

**Comment by lewangdev** [comment]
roles.json 中要使用 deployment name，不是 model name

**Comment by lewangdev** [comment]
如果使用 azure 的 openai 模型，推荐使用这个版本 `AZURE_OPENAI_VERSION: "2023-05-15"`，这个版本流式接口效果好一些

**Comment by sandycs-protoss** [comment]
好。问题解决了，分享一下
1、openai和auzre都要配置
2、OPENAI_OPENAI_TYPE: azure这一行的注释要去掉
3、配置deployment name，不是 model name
4、按键对应roles.json里的不同行。我的中间按钮对应6，我一直在改1

**Comment by lewangdev** [comment]
> 好。问题解决了，分享一下 1、openai和auzre都要配置 2、OPENAI_OPENAI_TYPE: azure这一行的注释要去掉 3、配置deployment name，不是 model name 4、按键对应roles.json里的不同行。我的中间按钮对应6，我一直在改1

小的一圈按键是角色，对应 roles.json 里面的每一个角色，中间大的按键是语音对话
