### ISSUE TITLE
使用MQTT 推送语言或文字让兔子朗读,  服务器上已经生成好语音文件,但是兔子没反应.

### ISSUE THREAD

**Issue by Tongvivi** [FoloToy/folotoy-server-self-hosting#82]
根据 MQTT 集成 这里推送文字,兔子没反应.

audio 目录已经生成了对应的语音文件,兔子没反应.

已经打开了  MQTT 集成接口
<img width="855" alt="截屏2023-12-09 19 49 25" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/53285628/9f554fd0-3c36-46fc-8681-7c93b4473c55">

已经成功发送命令
<img width="1232" alt="截屏2023-12-09 19 51 38" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/53285628/cf417e23-413c-498c-82e1-49f79cb5f866">

日志
folotoy-server-folotoy-1  | 2023-12-09 19:48:08,088 - DEBUG - Received /user/folotoy/XXXXXXXXX/thing/command/callAck: message data: {'msgId': 31, 'identifier': 'audioplay_cmd', 'result': 1}
folotoy-server-folotoy-1  | 2023-12-09 19:48:08,088 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['XXXXXXXXX']}
folotoy-server-folotoy-1  | 2023-12-09 19:48:09,613 - DEBUG - Received /user/folotoy/XXXXXXXXX/thing/command/callAck: message data: {'msgId': 33, 'identifier': 'audioplay', 'result': 1}
folotoy-server-folotoy-1  | 2023-12-09 19:48:09,614 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['XXXXXXXXX']}
folotoy-server-folotoy-1  | 2023-12-09 19:51:13,653 - DEBUG - Received /sys/folotoy/XXXXXXXXX/thing/command/call: message data: {'msgId': 100, 'identifier': 'iwantplay', 'inputParams': {'role': 1, 'text': '9999, 这是一个播放文字转语音的测试123 hi good 朋友'}}
folotoy-server-folotoy-1  | 2023-12-09 19:51:13,655 - DEBUG - Using selector: EpollSelector
folotoy-server-folotoy-1  | 2023-12-09 19:51:14,249 - DEBUG - TTS(edge-tts) request time cost: 0.59s
folotoy-server-folotoy-1  | 2023-12-09 19:51:14,254 - DEBUG - Publish topic: /user/folotoy/XXXXXXXXX/thing/command/call, msg: {"msgId": 35, "identifier": "iwantplay", "inputParams": {"url": "http:/XXXXXXXXX:8082/voice-a4321acff94d4787bf6a48b1fc110476.mp3"}}
folotoy-server-folotoy-1  | 2023-12-09 19:51:14,254 - DEBUG - Publish topic: /sys/folotoy/XXXXXXXXX/thing/command/callAck, msg: {"identifier": "iwantplay", "msgId": 100, "result": 1}
folotoy-server-folotoy-1  | 2023-12-09 19:51:17,150 - DEBUG - Received /user/folotoy/XXXXXXXXX/thing/command/callAck: message data: {'msgId': 35, 'identifier': 'iwantplay', 'result': 1}
folotoy-server-folotoy-1  | 2023-12-09 19:51:17,150 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['XXXXXXXXX']}
folotoy-server-folotoy-1  | 2023-12-09 19:54:08,001 - DEBUG - Received /sys/folotoy/XXXXXXXXX/thing/command/call: message data: {'msgId': 100, 'identifier': 'iwantplay', 'inputParams': {'role': 1, 'text': '9999, 这是一个播放文字转语音的测试123 hi good 朋友'}}
folotoy-server-folotoy-1  | 2023-12-09 19:54:08,003 - DEBUG - Using selector: EpollSelector
folotoy-server-folotoy-1  | 2023-12-09 19:54:09,547 - DEBUG - TTS(edge-tts) request time cost: 1.54s
folotoy-server-folotoy-1  | 2023-12-09 19:54:09,550 - DEBUG - Publish topic: /user/folotoy/XXXXXXXXX/thing/command/call, msg: {"msgId": 36, "identifier": "iwantplay", "inputParams": {"url": "http:/XXXXXXXXX:8082/voice-0d73f00f1bcd4e858c4944fec4b1bbaf.mp3"}}
folotoy-server-folotoy-1  | 2023-12-09 19:54:09,551 - DEBUG - Publish topic: /sys/folotoy/XXXXXXXXX/thing/command/callAck, msg: {"identifier": "iwantplay", "msgId": 100, "result": 1}
folotoy-server-folotoy-1  | 2023-12-09 19:54:12,677 - DEBUG - Received /user/folotoy/XXXXXXXXX/thing/command/callAck: message data: {'msgId': 36, 'identifier': 'iwantplay', 'result': 1}
folotoy-server-folotoy-1  | 2023-12-09 19:54:12,677 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['XXXXXXXXX']}
folotoy-server-folotoy-1  | 2023-12-09 19:56:15,931 - DEBUG - Received /sys/folotoy/XXXXXXXXX/thing/command/call: message data: {'msgId': 100, 'identifier': 'iwantplay', 'inputParams': {'role': 1, 'text': '9999, 这是一个播放文字转语音的测试123 hi good 朋友'}}
folotoy-server-folotoy-1  | 2023-12-09 19:56:15,936 - DEBUG - Using selector: EpollSelector
folotoy-server-folotoy-1  | 2023-12-09 19:56:16,544 - DEBUG - TTS(edge-tts) request time cost: 0.61s
folotoy-server-folotoy-1  | 2023-12-09 19:56:16,555 - DEBUG - Publish topic: /user/folotoy/XXXXXXXXX/thing/command/call, msg: {"msgId": 37, "identifier": "iwantplay", "inputParams": {"url": "http:/XXXXXXXXX:8082/voice-644505a7bafb4bf88a0a2acb75c3914d.mp3"}}
folotoy-server-folotoy-1  | 2023-12-09 19:56:16,555 - DEBUG - Publish topic: /sys/folotoy/XXXXXXXXX/thing/command/callAck, msg: {"identifier": "iwantplay", "msgId": 100, "result": 1}
folotoy-server-folotoy-1  | 2023-12-09 19:56:18,212 - DEBUG - Received /user/folotoy/XXXXXXXXX/thing/command/callAck: message data: {'msgId': 37, 'identifier': 'iwantplay', 'result': 1}
folotoy-server-folotoy-1  | 2023-12-09 19:56:18,212 - DEBUG - Command call ack: True, topic_tokens: {'#': [], '+': ['XXXXXXXXX']}

**Comment by lewangdev** [comment]
玩具的固件是什么版本？另外可以登录emqx看下玩具订阅了哪些主题

**Comment by Tongvivi** [comment]
<img width="1271" alt="截屏2023-12-09 21 54 45" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/53285628/536d0803-b927-4738-9a52-12d50d20c613">


/user/folotoy/a0a3b30fcd84/thing/command/call | 0 | 取消订阅
-- | -- | --
/user/folotoy/a0a3b30fcd84/thing/event/postAck

订阅了这2个主题.

玩具的固件怎么看?  玩具是米兔的,是不是版本比较老没更新?

**Comment by Tongvivi** [comment]
玩具是小米兔子
刷了最新的固件[folotoy-23.45.2.28-beta.bin]
(https://github.com/FoloToy/folotoy-bin/releases/download/23.45.2.28-beta/folotoy-23.45.2.28-beta.bin)

米兔玩具的日志里面 显示,语言文件已经下载到玩具机器里面了.
但是没有播放出来.

语音文件:
http://XXXXXXXXX:8082/voice-7b4a14f072dd4a3c96f2497719c2b28e.mp3

FSM=====================idle_enter==================================
I: [EVENT] ROBOT_IDLE
I: local audio url:/tip.mp3
{"msgId":5,"identifier":"press_small_btn","outParams":{"keyCode":5,"changed":1}}
I: MQTT Message[/user/folotoy/a0a3b30fcd84/thing/command/call]
{"msgId": 43, "identifier": "updatestartvoice", "inputParams": {"url": "http://XXXXXXXXX:8082/voice-038dd7bdd0994c6ba38ae2b8984e74e6.mp3", "keyCode": 5, "etag": "f6f6b5b25a18fad98abe16680be3d424"}}
set start voice to queue...
I: play start file...I: [EVENT] ROBOT_CHANGEVOICEI: local audio url:/start5.mp3
I: [EVENT] ROBOT_IDLEI: changeRoleSetting: 5 success!I: changeOldRoleSetting: 1 success!
I: MQTT Message[/user/folotoy/a0a3b30fcd84/thing/command/call]
{"msgId": 44, "identifier": "iwantplay", "inputParams": {"url": "http://XXXXXXXXX:8082/voice-5c3f2f5f96a944b68b53c83bdc69155e.mp3"}}
I: MQTT Message[/user/folotoy/a0a3b30fcd84/thing/command/call]
{"msgId": 45, "identifier": "iwantplay", "inputParams": {"url": "http://XXXXXXXXX:8082/voice-9df7eb223ede42c79e999715ffe59ab5.mp3"}}
I: MQTT Message[/user/folotoy/a0a3b30fcd84/thing/command/call]
{"msgId": 46, "identifier": "iwantplay", "inputParams": {"url": "http://XXXXXXXXX:8082/voice-7b4a14f072dd4a3c96f2497719c2b28e.mp3"}}

**Comment by lewangdev** [comment]
刷固件最新版：

https://github.com/FoloToy/folotoy-bin/releases/tag/23.46.3.1

**Comment by Tongvivi** [comment]
感谢! !  问题解决了.!
