### ISSUE TITLE
群晖上挂载服务器，有什么办法能让群晖访问API？

### ISSUE THREAD

**Issue by NorthernWinter** [FoloToy/folotoy-server-self-hosting#86]
我现在按1会有语音提示，但是无法对话
log如下
I: record endbutton pressed
FSM=====================record_exit==================================
[I] AnalogAudio.h : 64 - virtual void audio_tools::AnalogAudioStream::end()
[I] AnalogAudioESP32.h : 137 - end
FSM=====================atob========================================
FSM=====================wait_enter==================================
I: [EVENT] ROBOT_THINK
I: MQTT Message[/user/folotoy/08d1f9c6a4f8/thing/command/call]
{"msgId": 9, "identifier": "audioplay_cmd", "inputParams": {"recordingId": 37, "total": 0}}
FSM=====================wait_exit==================================FSM=====================atob========================================
FSM=====================idle_enter==================================
I: [EVENT] ROBOT_IDLE
Timeout for 30 seconds!
我理解是群晖无法访问openai API，看API使用记录也是0
我的硬件环境是群晖---路由器--外网
路由器挂了科学插件，指定了群晖的IP走全局翻墙
但是看来不好用，还有什么好办法吗？

**Comment by lewangdev** [comment]
看一下群晖上的日志，8085/udp端口打开了没？

**Comment by NorthernWinter** [comment]
换成云服务器了，另开单问问题
