### ISSUE TITLE
有哪些语音可以替换？

### ISSUE THREAD

**Issue by NorthernWinter** [FoloToy/folotoy-server-self-hosting#88]
想换一个语音，都有哪些能替换的？有没有列表之类的可以参考一下

**Comment by lewangdev** [comment]
参考文档：[tts语音配置](https://docs.folotoy.com/zh/docs/configuration/roles_config#%E6%96%87%E5%AD%97%E8%BD%AC%E8%AF%AD%E9%9F%B3-tts-text-to-sound-%E8%A7%92%E8%89%B2%E7%BA%A7%E5%88%AB%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)，看每个的 voice_name 字段

<img width="1105" alt="image" src="https://github.com/FoloToy/folotoy-server-self-hosting/assets/1455685/29ba9049-4870-43b9-88a8-b8961948fa7a">

**Comment by NorthernWinter** [comment]
好的谢谢
