### ISSUE TITLE
fly.io搭建好了无法连接

### ISSUE THREAD

**Issue by wgsxsm** [FoloToy/folotoy-server-self-hosting#95]
日志信息输出如下：
`  "mqtt": {
    "enable": true,
    "broker": "不带http的my-app-name.fly.dev",
    "port": 1883,
    "cid": "S**********N",
    "username": "S**********N",
    "password": "K*****E****Y"
  },
  "udpSpeechServer": {
    "address": "?上次配置好的ip?",
    "port": 8085
  }`

**Comment by wgsxsm** [comment]
比对配置信息也没看出什么问题
具体配置信息如下：
app = "<my-app-name>"
primary_region = "nrt"

[build]

[env]
  API_SERVER = "true"
  API_SERVER_BIND_ADDRESS = "0.0.0.0"
  API_SERVER_PORT = "8082"
  AUDIO_DOWNLOAD_URL = "http://<my-app-name>.fly.dev:8082"----感觉这里应该是https
  AUDIO_SAVE_PATH = "/audio"
  LLM_TYPE = "openai"
  LOG_LEVEL = "DEBUG"
  MQTT_BROKER_HOST = "127.0.0.1"
  MQTT_BROKER_PORT = "1883"
  MQTT_CLIENT_ID = "folotoy"
  MQTT_USERNAME = "folotoy"
  OPENAI_TTS_MODEL = "tts-1"
  OPENAI_WHISPER_MODEL = "whisper-1"
  ROLES_FILE_PATH = "/config/roles.json"
  SPEECH_UDP_SERVER_BIND_ADDRESS = "fly-global-services"
  SPEECH_UDP_SERVER_HOST = "<my-app-name>.fly.dev"
  SPEECH_UDP_SERVER_PORT = "8085"
  STT_TYPE = "openai-whisper"
  TTS_TYPE = "edge-tts"
  TZ = "Asia/Shanghai"

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "udp"
  internal_port = 8085

  [[services.ports]]
    port = 8085

**Comment by lewangdev** [comment]
试试这个能不能用：

MQTT Server Address: folotoy-server-test.fly.dev
MQTT Server Port: 1883

**Comment by wgsxsm** [comment]
> 试试这个能不能用：
> 
> MQTT Server Address: folotoy-server-test.fly.dev MQTT Server Port: 1883

一样的，还是udpSpeechServer这个指向了上一次正确的配置的ip

**Comment by wgsxsm** [comment]
> 试试这个能不能用：
> 
> MQTT Server Address: folotoy-server-test.fly.dev MQTT Server Port: 1883

重新刷机为最新固件后，配网之后，udpSpeechServer指向变了，变成另一个ip了

**Comment by lewangdev** [comment]
> > 试试这个能不能用：
> 
> > 
> 
> > MQTT Server Address: folotoy-server-test.fly.dev MQTT Server Port: 1883
> 
> 
> 
> 重新刷机为最新固件后，配网之后，udpSpeechServer指向变了，变成另一个ip了

是的，这个是ip的，不能使用吗

**Comment by wgsxsm** [comment]
> > > 试试这个能不能用：
> > 
> > 
> > > 
> > 
> > 
> > > MQTT Server Address: folotoy-server-test.fly.dev MQTT Server Port: 1883
> > 
> > 
> > 重新刷机为最新固件后，配网之后，udpSpeechServer指向变了，变成另一个ip了
> 
> 是的，这个是ip的，不能使用吗

对 提示Please check your config!

**Comment by wgsxsm** [comment]
fly io要配置个ipv4
