### ISSUE TITLE
如何播放自定义 mp3

### ISSUE THREAD

**Issue by fungo** [FoloToy/folotoy-server-self-hosting#97]
https://github.com/FoloToy/folotoy-bin/releases/tag/23.46.3.1

在 folotoy-bin 23.46.3.1 release notes 有提到

> 支持播放自定义 mp3 链接和指定角色播报文字

请问这个功能怎么使用？
比如我想让改装后的小兔子，继续有播放儿歌的能力，是不是可以用这个功能来实现呢。

**Comment by lewangdev** [comment]
参考这里，https://docs.folotoy.com/zh/docs/integrations/mqtt

**Comment by fungo** [comment]
多谢回复，我不懂 MQTT 开发，不过这个我理解是集成另外的 MQTT 到 folotoy 中来，让第三方的平台，能对小兔子下达指令。

我本来想的是，还是通过小兔子本身下达指令，从服务上拉对应的 mp3 下来播放。整个流程大概可能是这样：

1. 用某个角色，或者某个指令前缀，对小兔兔说，“播放儿歌”
2. 服务器侧进行 stt 后，把文本中的 “播放儿歌” 关键字识别出来
3. 关键字识别出来后，去预先设置的目录之类的地方，找到对应的 mp3 // 这一步取代原来和 chatgpt api 交互的步骤
4. 把 mp3 地址下发给小兔兔播放。

这样的话，通过改装，可以让小兔兔有了 AI 交流的能力，同时还能用原来的故事机能力。

**Comment by lewangdev** [comment]
目前要实现这个功能会比较绕，也是能做到的。

自己实现一个 openai 兼容的接口，用来接受兔子的语音请求，这个时候调用大模型处理之后，可能会得到一个音乐文件，并且返回一个empty的输出给兔子，这个时候兔子就不会回答问题并且立即进入空闲状态，然后推送一个mp3链接给兔子就会播放了。

后续我们会实现funtion-call或者添加相应配置来简化这个过程

**Comment by fungo** [comment]
期待后续的提升 😄
