### ISSUE TITLE
用1panel安装docker后出现错误，需要指教

### ISSUE THREAD

**Issue by cjg1982** [FoloToy/folotoy-server-self-hosting#99]
我已经开放了端口 修改了IP地址在容器中还是显示错误

![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/23011189/99249d35-3177-47ef-8702-cbf007953b58)

**Comment by cjg1982** [comment]
![image](https://github.com/FoloToy/folotoy-server-self-hosting/assets/23011189/0391e2e1-1a97-4234-9629-21d8f4489d0e)
我使用的是centos9 是不是这个原因呢？

**Comment by lewangdev** [comment]
emqx 启动失败了。方便的话把你的 1panel 访问地址和账号密码发给到我邮箱 lewang.dev@gmail.com，我帮你看一下

**Comment by cjg1982** [comment]
我搞定了，centos9 有些问题我换了debian10 可以用了
